# -*- coding: utf-8 -*-
"""
CalculateBasaltThickness.py

Purpose
-------
Use the h1/h2/h3/h3t results from CalculateH123.py step1 and ExtendCalculateH123.py step2
to calculate CE5-area basalt thickness or burial depth from DEM + CF rasters.

Main updates relative to the old CalculateUnitPixel.py
------------------------------------------------------
1. Basalt is defined as CF > 8.2, not CF < 8.2.
2. Rim type is judged only by the exact CF value at peak_row/peak_col, not by a local median window.
3. Filled crater filtering is NOT recalculated here. This script only reads
   profile_filled_flag / crater_filled_flag from the H123 CSV generated by
   CalculateH123.py and ExtendCalculateH123.py.
4. Unpenetrated basalt case is added:
   if both rims are basalt and all valid pixels between the two rims are basalt, the crater/profile
   is marked as basalt_only_unpenetrated; in the original three outputs, H3T is used as the direction-level thickness.
5. An extra old-method crater-summary shapefile is written after excluding H3T-derived unpenetrated basalt directions,
   so it can be used as a cleaner interpolation input.
6. The script writes annotated CSV outputs and point/crater shapefiles.

Expected inputs
---------------
- DEM raster: Database/CE5/CE5_dem.tif
- CF raster : Database/CE5/CE5_CF.tif
- Step1 CSV : Database/CE5/yolo/chickin/step1/all_yolo_h123.csv
- Step2 CSV : Database/CE5/yolo/chickin/step2/all_yolo_h123.csv

Example
-------
python scripts/CalculateBasaltThickness.py ^
  --dem Database/CE5/CE5_dem.tif ^
  --cf Database/CE5/CE5_CF.tif ^
  --step1-csv Database/CE5/yolo/chickin/step1/all_yolo_h123.csv ^
  --step2-csv Database/CE5/yolo/chickin/step2/all_yolo_h123.csv ^
  --out Database/CE5/yolo/chickin/basalt_thickness
"""

import argparse
import math
from pathlib import Path
from typing import Dict, List, Optional, Tuple

import numpy as np
import pandas as pd
import rasterio
from rasterio.windows import Window
from rasterio.transform import xy

try:
    import geopandas as gpd
    from shapely.geometry import Point
    HAS_GPD = True
except Exception:
    HAS_GPD = False


# ============================================================
# USER CONFIGURATION: edit paths and core thresholds here
# ============================================================
# Input rasters
DEFAULT_DEM = Path(r"Database/CE5/CE5_dem.tif")
DEFAULT_CF = Path(r"Database/CE5/CE5_CF.tif")

# H123 result CSVs generated before this script
# step1: output from CalculateH123.py
# step2: output from ExtendCalculateH123.py
DEFAULT_STEP1_CSV = Path(r"Database/CE5/yolo/chickin/step1/all_yolo_h123.csv")
DEFAULT_STEP2_CSV = Path(r"Database/CE5/yolo/chickin/step2/all_yolo_h123.csv")

# Output folder for basalt thickness results
DEFAULT_OUT_DIR = Path(r"Database/CE5/yolo/chickin/basalt_thickness")

# Basalt criterion. In this project, CF > 8.2 is treated as basalt.
BASALT_CF_THRESHOLD = 8.2

# Basalt transition rule used in this version.
# - Basalt is CF > 8.2.
# - For a basalt rim, the lower boundary is represented by the first inward
#   non-basalt pixel center (CF <= 8.2), not by the previous basalt pixel.
# - For a non-basalt rim, the upper boundary is the first inward basalt pixel
#   center (CF > 8.2), and the lower boundary is the next inward non-basalt
#   pixel center (CF <= 8.2). A single basalt pixel is still accepted.
# This constant is kept only for backward-compatible diagnostic columns.
MAX_CONSECUTIVE_NONBASALT_GAP = 2
MIN_BASALT_PIXELS_FOR_THICKNESS = 1

# Crater-level aggregation thresholds.
# These two values come from the MATLAB IQR upper-fence statistics:
#   relative_spread_threshold = Q3 + 1.5 * IQR = 3.442
#   rel_dev_threshold         = Q3 + 1.5 * IQR = 2.011
# relative_spread is only a trigger for direction-level outlier checking;
# it does NOT remove the whole crater.
# rel_dev is used to identify direction-level outliers.
RELATIVE_SPREAD_THRESHOLD = 3.442
REL_DEV_THRESHOLD = 2.011

# Data-driven thresholds used by the sequential low-tail aggregation rule.
# These values were derived from the current Thickness.csv / crater-summary
# direction-thickness distribution:
#   n == 2:
#       pair_ratio = min(T1,T2) / max(T1,T2)
#       Otsu automatic threshold = 0.496
#   n >= 3:
#       low_ratio = min_value / median(other directions)
#       Otsu automatic threshold = 0.477
#
# The sequential low-tail rule uses PAIR_RATIO_THRESHOLD and LOW_RATIO_THRESHOLD.
# HIGH_PAIR_DIFF_THRESHOLD is kept only for backward compatibility with older
# function signatures/comments; the revised sequential rule does not require
# the two high values to be close before removing a clearly low-tail value.
PAIR_RATIO_THRESHOLD = 0.496
LOW_RATIO_THRESHOLD = 0.477
HIGH_PAIR_DIFF_THRESHOLD = 0.569

# User rule for unpenetrated/full-basalt profiles:
# if a basalt profile reaches the midpoint without a non-basalt lower boundary,
# use H3T as the direction-level thickness.
# This is kept for the original three outputs:
#   all_basalt_points.shp
#   basalt_thickness_points.shp
#   basalt_thickness_crater_summary.shp
USE_H3T_FOR_UNPENETRATED_BASALT = True

# Additional old-method comparison output:
# create one extra crater-level shapefile that discards direction records
# whose thickness was supplied from H3T for an unpenetrated basalt case.
# This keeps the original three shapefiles unchanged and provides an
# interpolation input that does not use artificial H3T thickness for
# all-basalt / unpenetrated-basalt profiles.
WRITE_OLDMETHOD_NO_H3T_UNPENETRATED_SUMMARY = True
OLDMETHOD_EXCLUDED_THICKNESS_SOURCE = "h3t_for_unpenetrated_basalt"

# Invalid raster value handling
INVALID_LOW = -3e10
MOON_RADIUS_M = 1737400.0

# Filled-crater flags are inherited from H123 CSVs.
# This script does NOT recalculate filled craters.
# Required CSV fields if filled filtering is needed:
#   profile_filled_flag, crater_filled_flag

# -----------------------------
# Basic utilities
# -----------------------------
def clean_values(values, invalid_low=INVALID_LOW, invalid_zero=False):
    arr = np.asarray(values, dtype=float).copy()
    arr[~np.isfinite(arr)] = np.nan
    arr[arr < invalid_low] = np.nan
    if invalid_zero:
        arr[arr == 0] = np.nan
    return arr


def safe_float(v, default=np.nan):
    try:
        if pd.isna(v):
            return default
        return float(v)
    except Exception:
        return default


def safe_int(v) -> Optional[int]:
    try:
        if pd.isna(v):
            return None
        vv = float(v)
        if not np.isfinite(vv):
            return None
        return int(round(vv))
    except Exception:
        return None


def safe_bool(v, default=False) -> bool:
    if v is None:
        return bool(default)
    try:
        if pd.isna(v):
            return bool(default)
    except Exception:
        pass
    if isinstance(v, str):
        s = v.strip().lower()
        if s in ("1", "true", "yes", "y", "filled", "是"):
            return True
        if s in ("0", "false", "no", "n", "not_filled", "否", ""):
            return False
    try:
        return bool(float(v) != 0)
    except Exception:
        return bool(default)


def moon_distance_m(lon1, lat1, lon2, lat2, radius=MOON_RADIUS_M):
    lon1 = np.radians(lon1)
    lat1 = np.radians(lat1)
    lon2 = np.radians(lon2)
    lat2 = np.radians(lat2)
    dlon = lon2 - lon1
    dlat = lat2 - lat1
    a = np.sin(dlat / 2.0) ** 2 + np.cos(lat1) * np.cos(lat2) * np.sin(dlon / 2.0) ** 2
    c = 2.0 * np.arctan2(np.sqrt(a), np.sqrt(1.0 - a))
    return radius * c


def raster_is_geographic(src) -> bool:
    if src.crs is None:
        return True
    txt = str(src.crs).lower()
    return ("degree" in txt) or ("geogcs" in txt) or ("longlat" in txt) or ("4326" in txt)


def point_distance_from_coords(x1, y1, x2, y2, is_geo=True):
    if is_geo:
        return moon_distance_m(x1, y1, x2, y2)
    return float(math.hypot(x2 - x1, y2 - y1))


def read_h123_csv(path: Path, source_step: str) -> pd.DataFrame:
    if path is None or not path.exists():
        return pd.DataFrame()

    df = pd.read_csv(path, encoding="utf-8-sig", dtype={"name": str})
    df["source_step"] = source_step

    # Normalize required columns.
    required = [
        "name", "profile_type", "side", "reason",
        "peak_val", "outer_mean", "bottom_elev",
        "h1", "h2", "h3", "h3t",
        "line_dem_row", "line_dem_col",
        "center_row", "center_col",
        "peak_row", "peak_col",
        "bottom_row", "bottom_col",
        "peak_global", "bottom_global"
    ]
    for c in required:
        if c not in df.columns:
            df[c] = np.nan

    # Keep only valid h123 records by default.
    if "reason" in df.columns:
        df = df[df["reason"].astype(str).str.lower().eq("ok")].copy()

    df["profile_type"] = df["profile_type"].astype(str).str.lower()
    df["side"] = df["side"].astype(str).str.lower()
    return df


def combine_h123(step1_csv: Path, step2_csv: Path) -> pd.DataFrame:
    dfs = []
    s1 = read_h123_csv(step1_csv, "step1")
    s2 = read_h123_csv(step2_csv, "step2")
    if not s1.empty:
        dfs.append(s1)
    if not s2.empty:
        dfs.append(s2)

    if not dfs:
        raise FileNotFoundError("No valid step1/step2 h123 CSV records were loaded.")

    df = pd.concat(dfs, ignore_index=True)

    # If duplicates exist, prefer step2 because it is usually a remedial calculation.
    df["_source_priority"] = df["source_step"].map({"step1": 1, "step2": 2}).fillna(0)
    df = df.sort_values(["name", "profile_type", "side", "_source_priority"])
    df = df.drop_duplicates(subset=["name", "profile_type", "side"], keep="last").copy()
    df = df.drop(columns=["_source_priority"])
    return df


def read_profile_segment(src, profile_type: str, fixed_index: int, start_global: int, end_global: int):
    """
    Read a row or column segment from a raster. Returns values, rows, cols.
    start_global/end_global are DEM row indices for col profiles and DEM col indices for row profiles.
    """
    start_global = int(start_global)
    end_global = int(end_global)
    lo = min(start_global, end_global)
    hi = max(start_global, end_global)

    if profile_type == "row":
        row = int(fixed_index)
        if row < 0 or row >= src.height:
            return np.array([]), np.array([], dtype=int), np.array([], dtype=int)
        lo = max(0, lo)
        hi = min(src.width - 1, hi)
        if hi < lo:
            return np.array([]), np.array([], dtype=int), np.array([], dtype=int)
        arr = src.read(1, window=Window(lo, row, hi - lo + 1, 1))[0, :]
        cols = np.arange(lo, hi + 1, dtype=int)
        rows = np.full(cols.shape, row, dtype=int)
    else:
        col = int(fixed_index)
        if col < 0 or col >= src.width:
            return np.array([]), np.array([], dtype=int), np.array([], dtype=int)
        lo = max(0, lo)
        hi = min(src.height - 1, hi)
        if hi < lo:
            return np.array([]), np.array([], dtype=int), np.array([], dtype=int)
        arr = src.read(1, window=Window(col, lo, 1, hi - lo + 1))[:, 0]
        rows = np.arange(lo, hi + 1, dtype=int)
        cols = np.full(rows.shape, col, dtype=int)

    arr = clean_values(arr, invalid_low=INVALID_LOW, invalid_zero=False)

    # Preserve requested direction.
    if start_global > end_global:
        arr = arr[::-1]
        rows = rows[::-1]
        cols = cols[::-1]

    return arr, rows, cols


def get_raster_value(src, row: int, col: int) -> float:
    if row is None or col is None:
        return np.nan
    row = int(row)
    col = int(col)
    if row < 0 or row >= src.height or col < 0 or col >= src.width:
        return np.nan
    val = src.read(1, window=Window(col, row, 1, 1))[0, 0]
    val = clean_values([val], invalid_low=INVALID_LOW, invalid_zero=False)[0]
    return float(val) if np.isfinite(val) else np.nan


def index_global_for_record(rec: pd.Series) -> Optional[int]:
    profile_type = str(rec.get("profile_type", "")).lower()
    if profile_type == "row":
        return safe_int(rec.get("peak_col", np.nan))
    if profile_type == "col":
        return safe_int(rec.get("peak_row", np.nan))
    return None


def fixed_index_for_record(rec: pd.Series) -> Optional[int]:
    profile_type = str(rec.get("profile_type", "")).lower()
    if profile_type == "row":
        return safe_int(rec.get("line_dem_row", rec.get("peak_row", np.nan)))
    if profile_type == "col":
        return safe_int(rec.get("line_dem_col", rec.get("peak_col", np.nan)))
    return None


def bottom_global_for_record(rec: pd.Series) -> Optional[int]:
    profile_type = str(rec.get("profile_type", "")).lower()
    if profile_type == "row":
        return safe_int(rec.get("bottom_col", np.nan))
    if profile_type == "col":
        return safe_int(rec.get("bottom_row", np.nan))
    return None


def adjacent_slope_ratio_le_threshold(dem_src, dem_vals, rows, cols, threshold_deg=1.0):
    dem_vals = clean_values(dem_vals, invalid_low=INVALID_LOW, invalid_zero=False)
    if len(dem_vals) < 2:
        return np.nan, 0, 0

    xs, ys = xy(dem_src.transform, rows, cols, offset="center")
    xs = np.asarray(xs, dtype=float)
    ys = np.asarray(ys, dtype=float)
    is_geo = raster_is_geographic(dem_src)

    slopes = []
    for i in range(len(dem_vals) - 1):
        z1 = dem_vals[i]
        z2 = dem_vals[i + 1]
        if not (np.isfinite(z1) and np.isfinite(z2)):
            continue
        dist = point_distance_from_coords(xs[i], ys[i], xs[i + 1], ys[i + 1], is_geo=is_geo)
        if not np.isfinite(dist) or dist <= 0:
            continue
        slopes.append(abs(math.degrees(math.atan((z2 - z1) / dist))))

    if not slopes:
        return np.nan, 0, 0

    slopes = np.asarray(slopes, dtype=float)
    le_count = int(np.sum(slopes <= threshold_deg))
    valid_count = int(slopes.size)
    return float(le_count / valid_count), le_count, valid_count


def profile_key(rec: pd.Series):
    return (str(rec.get("name")), str(rec.get("profile_type")).lower())


def build_profile_diagnostics(df: pd.DataFrame, dem_src, cf_src) -> Dict[Tuple[str, str], Dict]:
    """
    For each crater + profile_type, this function only reads filled flags from the H123 CSV
    and calculates the CF-based unpenetrated-basalt diagnostic. It does NOT recalculate the
    filled-crater slope criterion here.
    """
    diag: Dict[Tuple[str, str], Dict] = {}

    for key, sub in df.groupby(["name", "profile_type"], sort=False):
        name, profile_type = key
        left = sub[sub["side"].eq("left")]
        right = sub[sub["side"].eq("right")]

        profile_filled_flag = False
        crater_filled_flag = False
        filled_ratio_vals = []
        filled_le_count_vals = []
        filled_valid_count_vals = []

        for _, r in sub.iterrows():
            profile_filled_flag = profile_filled_flag or safe_bool(r.get("profile_filled_flag", False), False)
            crater_filled_flag = crater_filled_flag or safe_bool(r.get("crater_filled_flag", False), False)
            rv = safe_float(r.get("filled_slope_ratio_le1", np.nan))
            if np.isfinite(rv):
                filled_ratio_vals.append(rv)
            le = safe_float(r.get("filled_slope_le1_count", np.nan))
            vc = safe_float(r.get("filled_slope_valid_count", np.nan))
            if np.isfinite(le):
                filled_le_count_vals.append(int(le))
            if np.isfinite(vc):
                filled_valid_count_vals.append(int(vc))

        info = {
            "name": name,
            "profile_type": profile_type,
            "profile_has_two_rims": False,
            "left_peak_global": np.nan,
            "right_peak_global": np.nan,
            "rim_midpoint_global": np.nan,
            "filled_slope_ratio_le1": float(np.nanmax(filled_ratio_vals)) if filled_ratio_vals else np.nan,
            "filled_slope_le1_count": int(max(filled_le_count_vals)) if filled_le_count_vals else 0,
            "filled_slope_valid_count": int(max(filled_valid_count_vals)) if filled_valid_count_vals else 0,
            "profile_filled_flag": bool(profile_filled_flag),
            "crater_filled_flag_from_csv": bool(crater_filled_flag),
            "profile_between_valid_cf_count": 0,
            "profile_between_basalt_count": 0,
            "profile_between_nonbasalt_count": 0,
            "profile_all_between_basalt": False,
            "profile_both_rims_basalt": False,
            "profile_basalt_only_unpenetrated": False,
        }

        if left.empty or right.empty:
            diag[key] = info
            continue

        left_rec = left.iloc[0]
        right_rec = right.iloc[0]

        fixed = fixed_index_for_record(left_rec)
        left_peak_g = index_global_for_record(left_rec)
        right_peak_g = index_global_for_record(right_rec)
        if fixed is None or left_peak_g is None or right_peak_g is None:
            diag[key] = info
            continue

        info["left_peak_global"] = int(left_peak_g)
        info["right_peak_global"] = int(right_peak_g)
        info["rim_midpoint_global"] = int(round((float(left_peak_g) + float(right_peak_g)) / 2.0))

        start_g = min(left_peak_g, right_peak_g)
        end_g = max(left_peak_g, right_peak_g)

        cf_vals, _, _ = read_profile_segment(cf_src, profile_type, fixed, start_g, end_g)
        info["profile_has_two_rims"] = True

        cf_vals = clean_values(cf_vals, invalid_low=INVALID_LOW, invalid_zero=False)
        valid_cf = cf_vals[np.isfinite(cf_vals)]
        basalt_mask = valid_cf > BASALT_CF_THRESHOLD
        info["profile_between_valid_cf_count"] = int(valid_cf.size)
        info["profile_between_basalt_count"] = int(np.sum(basalt_mask)) if valid_cf.size else 0
        info["profile_between_nonbasalt_count"] = int(np.sum(~basalt_mask)) if valid_cf.size else 0
        info["profile_all_between_basalt"] = bool(valid_cf.size > 0 and np.all(basalt_mask))

        left_cf = get_raster_value(cf_src, safe_int(left_rec.get("peak_row")), safe_int(left_rec.get("peak_col")))
        right_cf = get_raster_value(cf_src, safe_int(right_rec.get("peak_row")), safe_int(right_rec.get("peak_col")))
        info["left_peak_cf"] = left_cf
        info["right_peak_cf"] = right_cf
        info["profile_both_rims_basalt"] = bool(np.isfinite(left_cf) and np.isfinite(right_cf) and
                                                left_cf > BASALT_CF_THRESHOLD and right_cf > BASALT_CF_THRESHOLD)

        info["profile_basalt_only_unpenetrated"] = bool(
            info["profile_both_rims_basalt"] and info["profile_all_between_basalt"]
        )

        diag[key] = info

    return diag


def sample_peak_to_bottom(dem_src, cf_src, rec: pd.Series):
    """
    Legacy helper. Kept for compatibility only.
    New basalt-thickness extraction uses sample_peak_to_midpoint(), not this function.
    """
    profile_type = str(rec["profile_type"]).lower()
    fixed = fixed_index_for_record(rec)
    peak_g = index_global_for_record(rec)
    bottom_g = bottom_global_for_record(rec)

    if fixed is None or peak_g is None or bottom_g is None:
        return None

    dem_vals, rows, cols = read_profile_segment(dem_src, profile_type, fixed, peak_g, bottom_g)
    cf_vals, _, _ = read_profile_segment(cf_src, profile_type, fixed, peak_g, bottom_g)

    if len(dem_vals) == 0 or len(cf_vals) == 0:
        return None

    n = min(len(dem_vals), len(cf_vals))
    return dem_vals[:n], cf_vals[:n], rows[:n], cols[:n]


def midpoint_global_for_record(rec: pd.Series, profile_info: Dict) -> Optional[int]:
    """
    Return the inward search end index.

    Preferred rule: use the midpoint between the two rim/highest points of the
    current row/col profile.

    Fallback rule: if only one side is available and the two-rim midpoint cannot
    be defined, use the YOLO/core center line index from the H123 CSV. This
    prevents otherwise valid one-sided records from being discarded as
    invalid_peak_to_midpoint_profile.
    """
    mid = safe_int(profile_info.get("rim_midpoint_global", np.nan))
    if mid is not None:
        return mid

    profile_type = str(rec.get("profile_type", "")).lower()
    if profile_type == "row":
        return safe_int(rec.get("center_col", np.nan))
    if profile_type == "col":
        return safe_int(rec.get("center_row", np.nan))
    return None

def sample_peak_to_midpoint(dem_src, cf_src, rec: pd.Series, profile_info: Dict):
    """
    Read DEM/CF from one rim peak to the midpoint between the two rim peaks.
    Direction is preserved: index 0 is always the current rim peak, and the last
    element is the rim-to-rim midpoint.
    """
    profile_type = str(rec["profile_type"]).lower()
    fixed = fixed_index_for_record(rec)
    peak_g = index_global_for_record(rec)
    mid_g = midpoint_global_for_record(rec, profile_info)

    if fixed is None or peak_g is None or mid_g is None:
        return None

    dem_vals, rows, cols = read_profile_segment(dem_src, profile_type, fixed, peak_g, mid_g)
    cf_vals, _, _ = read_profile_segment(cf_src, profile_type, fixed, peak_g, mid_g)

    if len(dem_vals) == 0 or len(cf_vals) == 0:
        return None

    n = min(len(dem_vals), len(cf_vals))
    return dem_vals[:n], cf_vals[:n], rows[:n], cols[:n], int(mid_g)


def depth_from_peak_formula(peak_val: float, h1: float, elev: float) -> float:
    """
    Project formula used in previous scripts:
        depth = 0.8 * ((peak_val - elev) - 0.2 * h1)
    """
    return float(0.8 * ((float(peak_val) - float(elev)) - 0.2 * float(h1)))


def trace_basalt_interval_until_gap(search_idx, basalt_mask,
                                    max_gap=MAX_CONSECUTIVE_NONBASALT_GAP,
                                    start_idx=None):
    """
    Trace the first basalt interval along the inward search direction.

    After the first basalt pixel is reached, continue inward only until more
    than `max_gap` consecutive non-basalt pixels appear. Later basalt pixels
    after that terminating gap are ignored.

    The returned lower/end basalt boundary is always ``last_basalt``: the last
    basalt pixel before the terminating non-basalt gap. The first non-basalt
    pixel of the terminating gap is stored only for diagnostics.
    """
    idxs = [int(i) for i in list(search_idx)]
    out = {
        "found": False,
        "first_basalt": np.nan,
        "last_basalt": np.nan,
        "basalt_count_in_interval": 0,
        "terminated_by_gap": False,
        "stop_gap_first_idx": np.nan,
        "stop_gap_count": 0,
        "reached_search_end": False,
    }

    if start_idx is None:
        first = None
        start_pos = None
        for pos, i in enumerate(idxs):
            if bool(basalt_mask[i]):
                first = int(i)
                start_pos = int(pos)
                break
        if first is None:
            return out
    else:
        first = int(start_idx)
        if first in idxs:
            start_pos = idxs.index(first)
        else:
            idxs = [first] + idxs
            start_pos = 0

    out["found"] = True
    out["first_basalt"] = int(first)

    gap_count = 0
    gap_first = None
    last_basalt = int(first) if bool(basalt_mask[first]) else None
    basalt_count = 1 if bool(basalt_mask[first]) else 0

    for i in idxs[start_pos + 1:]:
        i = int(i)
        if bool(basalt_mask[i]):
            last_basalt = int(i)
            basalt_count += 1
            gap_count = 0
            gap_first = None
        else:
            if gap_count == 0:
                gap_first = int(i)
            gap_count += 1
            if gap_count > int(max_gap):
                out["terminated_by_gap"] = True
                out["stop_gap_first_idx"] = int(gap_first)
                out["stop_gap_count"] = int(gap_count)
                break

    if last_basalt is not None:
        out["last_basalt"] = int(last_basalt)
    out["basalt_count_in_interval"] = int(basalt_count)
    out["reached_search_end"] = not bool(out["terminated_by_gap"])
    if not bool(out["terminated_by_gap"]):
        out["stop_gap_count"] = int(gap_count)
        out["stop_gap_first_idx"] = int(gap_first) if gap_first is not None else np.nan
    return out


def calculate_direction_record(dem_src, cf_src, rec: pd.Series, profile_info: Dict, crater_filled_flag: bool) -> Dict:
    """
    Calculate basalt thickness for one direction using the user's corrected
    midpoint-limited transition rule.

    Search range
    ------------
    Current rim peak -> midpoint between the two rim peaks. If the opposite rim
    is missing, fall back to the profile center from the H123 CSV.

    Basalt rim, peak_cf > 8.2
    -------------------------
    Upper boundary: rim peak center.
    Lower boundary: first inward non-basalt pixel center (CF <= 8.2).
    If no such non-basalt pixel is reached before the search end, the basalt is
    treated as unpenetrated; this version uses H3T as the direction-level thickness.

    Non-basalt rim, peak_cf <= 8.2
    ------------------------------
    Upper boundary: first inward basalt pixel center (CF > 8.2).
    Lower boundary: first inward non-basalt pixel center after that basalt pixel
    (CF <= 8.2). A single basalt pixel is still accepted.
    If no basalt pixel is found, the crater/profile did not reach basalt. If a
    basalt pixel is found but no following non-basalt pixel is found before the
    search end, the layer is treated as unpenetrated; this version uses H3T as the direction-level thickness.

    Filled-crater flags are retained as diagnostic attributes only; they do not
    exclude records in this version.
    """
    name = str(rec["name"])
    profile_type = str(rec["profile_type"]).lower()
    side = str(rec["side"]).lower()

    peak_row = safe_int(rec.get("peak_row"))
    peak_col = safe_int(rec.get("peak_col"))

    h1 = safe_float(rec.get("h1"))
    peak_val = safe_float(rec.get("peak_val"))
    old_h2_bottom = safe_float(rec.get("h2"))

    peak_cf = get_raster_value(cf_src, peak_row, peak_col)
    rim_type = "unknown"
    if np.isfinite(peak_cf):
        rim_type = "basalt_rim" if peak_cf > BASALT_CF_THRESHOLD else "nonbasalt_rim"

    out = rec.to_dict()
    out.update({
        "peak_cf": peak_cf,
        "basalt_threshold_rule": f"CF>{BASALT_CF_THRESHOLD}",
        "rim_type_new": rim_type,
        "filled_slope_ratio_le1": profile_info.get("filled_slope_ratio_le1", np.nan),
        "filled_slope_le1_count": profile_info.get("filled_slope_le1_count", 0),
        "filled_slope_valid_count": profile_info.get("filled_slope_valid_count", 0),
        "profile_filled_flag": bool(profile_info.get("profile_filled_flag", False)),
        "crater_filled_flag": bool(crater_filled_flag),
        "profile_basalt_only_unpenetrated": bool(profile_info.get("profile_basalt_only_unpenetrated", False)),
        "profile_all_between_basalt": bool(profile_info.get("profile_all_between_basalt", False)),
        "profile_between_valid_cf_count": profile_info.get("profile_between_valid_cf_count", 0),
        "profile_between_basalt_count": profile_info.get("profile_between_basalt_count", 0),
        "profile_between_nonbasalt_count": profile_info.get("profile_between_nonbasalt_count", 0),
        "left_peak_global": profile_info.get("left_peak_global", np.nan),
        "right_peak_global": profile_info.get("right_peak_global", np.nan),
        "rim_midpoint_global": profile_info.get("rim_midpoint_global", np.nan),
        "midpoint_source": "two_rim_midpoint" if np.isfinite(safe_float(profile_info.get("rim_midpoint_global", np.nan))) else "profile_center_fallback",
        "search_end_global": np.nan,
        "search_end_row": np.nan,
        "search_end_col": np.nan,
        "search_valid_count": 0,
        "search_basalt_count": 0,
        "search_nonbasalt_count": 0,
        "basalt_run_first_idx": np.nan,
        "basalt_run_last_idx": np.nan,
        "basalt_run_count": 0,
        "stop_gap_first_idx": np.nan,
        "stop_gap_count": 0,
        "max_nonbasalt_gap_allowed": MAX_CONSECUTIVE_NONBASALT_GAP,
        "search_limited_to": "rim_peak_to_two_rim_midpoint_or_center_fallback",
        "upper_boundary_idx": np.nan,
        "upper_boundary_elev": np.nan,
        "upper_boundary_row": np.nan,
        "upper_boundary_col": np.nan,
        "upper_boundary_cf": np.nan,
        "lower_boundary_idx": np.nan,
        "lower_boundary_elev": np.nan,
        "lower_boundary_row": np.nan,
        "lower_boundary_col": np.nan,
        "lower_boundary_cf": np.nan,
        "h_basalt_elev": np.nan,
        "h_basalt_row": np.nan,
        "h_basalt_col": np.nan,
        "h_basalt_cf": np.nan,
        "h_basalt_last_elev": np.nan,
        "h_basalt_last_row": np.nan,
        "h_basalt_last_col": np.nan,
        "h_basalt_last_cf": np.nan,
        "h2_basalt": np.nan,
        "h2_basalt_top": np.nan,
        "h2_basalt_bottom": np.nan,
        "basalt_top_depth": np.nan,
        "basalt_bottom_depth": np.nan,
        "thickness_or_depth": np.nan,
        "thickness_mode": "not_calculated",
        "calculation_status": "not_started",
        "contact_idx_in_peak_to_bottom": np.nan,
        "contact_cf": np.nan,
        "contact_note": "",
        "old_h2_to_bottom": old_h2_bottom,
        "cf_class": out.get("cf_class", "unknown"),
        "thk_ok": int(safe_bool(out.get("thk_ok", False), False)),
        "unpenetrated_flag": int(safe_bool(out.get("unpenetrated_flag", False), False)),
        "thickness_source": "cf_transition",
    })

    def _use_h3t_as_unpenetrated_thickness(mode: str, note: str):
        """
        User rule: for all-basalt / unpenetrated basalt profiles, use H3T as
        thickness_or_depth. The record is kept as a valid direction-level
        thickness record while still carrying the unpenetrated flag.
        """
        h3t_val = safe_float(rec.get("h3t", np.nan))
        class_name = "unpenetrated_all_basalt" if bool(profile_info.get("profile_basalt_only_unpenetrated", False)) else "unpenetrated_basalt_rim"

        if np.isfinite(h3t_val) and h3t_val > 0:
            out.update({
                "thickness_or_depth": float(h3t_val),
                "thickness_mode": mode,
                "calculation_status": "ok",
                "cf_class": class_name,
                "thk_ok": 1,
                "unpenetrated_flag": 1,
                "thickness_source": "h3t_for_unpenetrated_basalt",
                "contact_note": note,
            })
        else:
            out.update({
                "thickness_or_depth": np.nan,
                "thickness_mode": mode,
                "calculation_status": "invalid_h3t_for_unpenetrated_basalt",
                "cf_class": class_name,
                "thk_ok": 0,
                "unpenetrated_flag": 1,
                "thickness_source": "h3t_for_unpenetrated_basalt_failed",
                "contact_note": note + "; h3t is invalid, so thickness_or_depth remains NaN",
            })
        return out

    if rim_type == "unknown":
        out["calculation_status"] = "invalid_peak_cf"
        return out

    if not (np.isfinite(h1) and np.isfinite(peak_val)):
        out["calculation_status"] = "invalid_h1_or_peak_val"
        return out

    sampled = sample_peak_to_midpoint(dem_src, cf_src, rec, profile_info)
    if sampled is None:
        out["calculation_status"] = "invalid_peak_to_midpoint_profile"
        out["contact_note"] = "could not read peak-to-midpoint/profile-center segment; check peak index, fixed row/col, or center fallback"
        return out

    dem_vals, cf_vals, rows, cols, mid_g = sampled
    dem_vals = clean_values(dem_vals, invalid_low=INVALID_LOW, invalid_zero=False)
    cf_vals = clean_values(cf_vals, invalid_low=INVALID_LOW, invalid_zero=False)

    valid = np.isfinite(dem_vals) & np.isfinite(cf_vals)
    if np.sum(valid) == 0:
        out["calculation_status"] = "no_valid_peak_to_midpoint_values"
        return out

    basalt_mask = valid & (cf_vals > BASALT_CF_THRESHOLD)
    search_idx = np.array([i for i in range(1, len(cf_vals)) if valid[i]], dtype=int)
    search_basalt_idx = np.array([i for i in search_idx if basalt_mask[i]], dtype=int)
    search_nonbasalt_idx = np.array([i for i in search_idx if valid[i] and not basalt_mask[i]], dtype=int)

    out.update({
        "rim_midpoint_global": int(mid_g) if not np.isfinite(safe_float(out.get("rim_midpoint_global", np.nan))) else out.get("rim_midpoint_global"),
        "search_end_global": int(mid_g),
        "search_end_row": int(rows[-1]) if len(rows) else np.nan,
        "search_end_col": int(cols[-1]) if len(cols) else np.nan,
        "search_valid_count": int(search_idx.size),
        "search_basalt_count": int(search_basalt_idx.size),
        "search_nonbasalt_count": int(search_nonbasalt_idx.size),
    })

    if search_idx.size == 0:
        out["calculation_status"] = "no_valid_inward_pixels_to_midpoint"
        out["thickness_mode"] = "no_valid_inward_pixels"
        return out

    def _first_nonbasalt_after(pos0):
        for ii in search_idx:
            ii = int(ii)
            if ii <= int(pos0):
                continue
            if valid[ii] and not basalt_mask[ii]:
                return ii
        return None

    def _first_basalt():
        for ii in search_idx:
            ii = int(ii)
            if basalt_mask[ii]:
                return ii
        return None

    def _set_boundaries(upper_i, lower_i, mode, status, note, use_peak_as_upper=False):
        if use_peak_as_upper:
            upper_elev = float(peak_val)
            upper_row = peak_row
            upper_col = peak_col
            upper_cf = float(peak_cf) if np.isfinite(peak_cf) else np.nan
            upper_depth = 0.0
        else:
            upper_elev = float(dem_vals[upper_i])
            upper_row = int(rows[upper_i])
            upper_col = int(cols[upper_i])
            upper_cf = float(cf_vals[upper_i])
            upper_depth = depth_from_peak_formula(peak_val, h1, upper_elev)

        lower_elev = float(dem_vals[lower_i])
        lower_row = int(rows[lower_i])
        lower_col = int(cols[lower_i])
        lower_cf = float(cf_vals[lower_i])
        lower_depth = depth_from_peak_formula(peak_val, h1, lower_elev)

        if use_peak_as_upper:
            thickness = lower_depth
            h2_top = 0.0
        else:
            thickness = abs(lower_depth - upper_depth)
            h2_top = float(peak_val - upper_elev)

        out.update({
            "upper_boundary_idx": int(0 if use_peak_as_upper else upper_i),
            "upper_boundary_elev": upper_elev,
            "upper_boundary_row": upper_row,
            "upper_boundary_col": upper_col,
            "upper_boundary_cf": upper_cf,
            "lower_boundary_idx": int(lower_i),
            "lower_boundary_elev": lower_elev,
            "lower_boundary_row": lower_row,
            "lower_boundary_col": lower_col,
            "lower_boundary_cf": lower_cf,
            "h_basalt_elev": upper_elev if not use_peak_as_upper else lower_elev,
            "h_basalt_row": int(upper_row if not use_peak_as_upper else lower_row),
            "h_basalt_col": int(upper_col if not use_peak_as_upper else lower_col),
            "h_basalt_cf": float(upper_cf if not use_peak_as_upper else lower_cf),
            "h_basalt_last_elev": lower_elev,
            "h_basalt_last_row": lower_row,
            "h_basalt_last_col": lower_col,
            "h_basalt_last_cf": lower_cf,
            "h2_basalt": float(peak_val - lower_elev),
            "h2_basalt_top": h2_top,
            "h2_basalt_bottom": float(peak_val - lower_elev),
            "basalt_top_depth": upper_depth,
            "basalt_bottom_depth": lower_depth,
            "thickness_or_depth": thickness if thickness >= 0 else np.nan,
            "thickness_mode": mode,
            "calculation_status": status if thickness >= 0 else "negative_result_set_nan",
            "contact_idx_in_peak_to_bottom": int(lower_i if use_peak_as_upper else upper_i),
            "contact_cf": float(lower_cf if use_peak_as_upper else upper_cf),
            "contact_note": note,
        })
        return out

    # -----------------------------
    # Case A. Rim peak is basalt.
    # -----------------------------
    if rim_type == "basalt_rim":
        lower_i = None
        for ii in search_idx:
            ii = int(ii)
            if valid[ii] and not basalt_mask[ii]:
                lower_i = ii
                break

        out.update({
            "basalt_run_first_idx": 0,
            "basalt_run_last_idx": int(lower_i - 1) if lower_i is not None and lower_i > 0 else np.nan,
            "basalt_run_count": int(np.sum(basalt_mask[:lower_i])) if lower_i is not None else int(np.sum(basalt_mask)),
            "stop_gap_first_idx": int(lower_i) if lower_i is not None else np.nan,
            "stop_gap_count": 1 if lower_i is not None else 0,
        })

        if lower_i is None:
            if USE_H3T_FOR_UNPENETRATED_BASALT:
                return _use_h3t_as_unpenetrated_thickness(
                    mode="basalt_rim_unpenetrated_h3t_thickness",
                    note="basalt rim; no inward CF<=threshold pixel before midpoint/profile-center fallback; user rule uses h3t as thickness",
                )
            out["calculation_status"] = "excluded_basalt_unpenetrated_to_midpoint"
            out["thickness_mode"] = "basalt_rim_no_nonbasalt_to_midpoint"
            out["contact_note"] = "basalt rim; no inward CF<=threshold pixel before midpoint/profile-center fallback, so lower boundary was not reached"
            out["cf_class"] = "unpenetrated_all_basalt" if bool(profile_info.get("profile_basalt_only_unpenetrated", False)) else "unpenetrated_basalt_rim"
            out["unpenetrated_flag"] = 1
            out["thk_ok"] = 0
            return out

        return _set_boundaries(
            upper_i=0,
            lower_i=lower_i,
            mode="basalt_rim_thickness_first_nonbasalt_center",
            status="ok",
            note="basalt rim; lower boundary uses the center elevation of the first inward non-basalt pixel (CF<=threshold)",
            use_peak_as_upper=True,
        )

    # -----------------------------
    # Case B. Rim peak is not basalt.
    # -----------------------------
    first_basalt = _first_basalt()
    if first_basalt is None:
        out["calculation_status"] = "no_basalt_detected_to_midpoint"
        out["thickness_mode"] = "no_basalt_detected_before_midpoint"
        out["contact_note"] = "non-basalt rim; no inward CF>threshold pixel before midpoint/profile-center fallback"
        return out

    lower_i = _first_nonbasalt_after(first_basalt)

    out.update({
        "basalt_run_first_idx": int(first_basalt),
        "basalt_run_last_idx": int(first_basalt if lower_i is not None else (search_basalt_idx[-1] if search_basalt_idx.size else first_basalt)),
        "basalt_run_count": int(np.sum([basalt_mask[ii] for ii in search_idx if ii >= first_basalt and (lower_i is None or ii < lower_i)])),
        "stop_gap_first_idx": int(lower_i) if lower_i is not None else np.nan,
        "stop_gap_count": 1 if lower_i is not None else 0,
    })

    if lower_i is None:
        out.update({
            "upper_boundary_idx": int(first_basalt),
            "upper_boundary_elev": float(dem_vals[first_basalt]),
            "upper_boundary_row": int(rows[first_basalt]),
            "upper_boundary_col": int(cols[first_basalt]),
            "upper_boundary_cf": float(cf_vals[first_basalt]),
            "h_basalt_elev": float(dem_vals[first_basalt]),
            "h_basalt_row": int(rows[first_basalt]),
            "h_basalt_col": int(cols[first_basalt]),
            "h_basalt_cf": float(cf_vals[first_basalt]),
            "h2_basalt_top": float(peak_val - float(dem_vals[first_basalt])),
            "basalt_top_depth": depth_from_peak_formula(peak_val, h1, float(dem_vals[first_basalt])),
            "contact_idx_in_peak_to_bottom": int(first_basalt),
            "contact_cf": float(cf_vals[first_basalt]),
        })
        if USE_H3T_FOR_UNPENETRATED_BASALT:
            return _use_h3t_as_unpenetrated_thickness(
                mode="nonbasalt_rim_unpenetrated_h3t_thickness",
                note="non-basalt rim; basalt upper boundary was found, but no following CF<=threshold pixel before midpoint/profile-center fallback; user rule uses h3t as thickness",
            )
        out.update({
            "thickness_mode": "nonbasalt_rim_basalt_reaches_midpoint_no_lower_boundary",
            "calculation_status": "excluded_basalt_unpenetrated_to_midpoint",
            "contact_note": "non-basalt rim; basalt upper boundary was found, but no following CF<=threshold pixel before midpoint/profile-center fallback, so lower boundary was not reached",
            "cf_class": "unpenetrated_basalt_rim",
            "unpenetrated_flag": 1,
            "thk_ok": 0,
        })
        return out

    return _set_boundaries(
        upper_i=first_basalt,
        lower_i=lower_i,
        mode="nonbasalt_rim_thickness_first_basalt_to_first_nonbasalt_center",
        status="ok",
        note="non-basalt rim; upper boundary uses first inward basalt pixel center (CF>threshold), lower boundary uses the following first inward non-basalt pixel center (CF<=threshold); one-pixel basalt intervals are retained",
        use_peak_as_upper=False,
    )

def attach_felsic_felsic_profile_thickness(records_df: pd.DataFrame) -> pd.DataFrame:
    """
    Kept for backward compatibility.

    Earlier versions calculated profile_t_basalt only when both sides were
    nonbasalt_rim_burial_depth. After the 2026-05 midpoint revision, a non-basalt
    rim direction directly calculates true thickness from the first and last
    basalt pixels before the two-rim midpoint. Therefore profile_t_basalt is no
    longer needed as the main thickness field.
    """
    df = records_df.copy()
    if "profile_t_basalt" not in df.columns:
        df["profile_t_basalt"] = np.nan
    if "profile_t_basalt_status" not in df.columns:
        df["profile_t_basalt_status"] = "not_used_after_midpoint_revision"
    return df


def attach_h3_h3t_relative_error(df: pd.DataFrame) -> pd.DataFrame:
    """
    Add h3/h3t relative-error diagnostics following nihechengtu.m:
        rel_err = abs(h3 - h3t) / ((h3 + h3t) / 2)

    rel_err is stored as a fraction; rel_err_pct is percent. Records with
    rel_err >= 0.20 are removed from basalt_thickness_points.shp, while
    all_basalt_points.shp keeps all records.
    """
    out = df.copy()
    h3 = pd.to_numeric(out.get("h3", np.nan), errors="coerce")
    h3t = pd.to_numeric(out.get("h3t", np.nan), errors="coerce")
    thk = pd.to_numeric(out.get("thickness_or_depth", np.nan), errors="coerce")
    denom = (h3 + h3t) / 2.0
    valid = np.isfinite(h3) & np.isfinite(h3t) & np.isfinite(denom) & (denom != 0)
    rel_err = pd.Series(np.nan, index=out.index, dtype=float)
    rel_err.loc[valid] = np.abs(h3.loc[valid] - h3t.loc[valid]) / denom.loc[valid]
    out["h3_h3t_rel_err"] = rel_err
    out["h3_h3t_rel_err_pct"] = rel_err * 100.0
    out["h3_h3t_pass20"] = valid & np.isfinite(thk) & (rel_err < 0.20)
    return out


def fit_h3_vs_h3t_r2(df: pd.DataFrame) -> Dict[str, float]:
    x = pd.to_numeric(df.get("h3t", np.nan), errors="coerce").to_numpy(dtype=float)
    y = pd.to_numeric(df.get("h3", np.nan), errors="coerce").to_numpy(dtype=float)
    valid = np.isfinite(x) & np.isfinite(y)
    x = x[valid]
    y = y[valid]
    if x.size < 2 or np.nanstd(y) == 0:
        return {"n": int(x.size), "slope": np.nan, "intercept": np.nan, "r2": np.nan}
    p = np.polyfit(x, y, 1)
    yfit = np.polyval(p, x)
    ss_res = float(np.sum((y - yfit) ** 2))
    ss_tot = float(np.sum((y - np.mean(y)) ** 2))
    r2 = float(1.0 - ss_res / ss_tot) if ss_tot != 0 else np.nan
    return {"n": int(x.size), "slope": float(p[0]), "intercept": float(p[1]), "r2": r2}


def write_point_shp(df: pd.DataFrame, out_shp: Path, cf_src, only_pass20: bool = False):
    """
    Write point shapefile.

    all_basalt_points.shp:
      - all direction records; thk_dep may be NULL.
    basalt_thickness_points.shp:
      - only records with true thickness not NULL and h3/h3t relative error <20%.

    Geometry is always written at the rim peak (peak_row/peak_col), not at the
    basalt contact point. Contact rows/cols are stored only as attributes.
    """
    if not HAS_GPD:
        print("geopandas/shapely unavailable; skip shapefile output.")
        return

    use_df = df.copy()
    if only_pass20:
        if "h3_h3t_pass20" not in use_df.columns:
            use_df = attach_h3_h3t_relative_error(use_df)
        use_df = use_df[use_df["h3_h3t_pass20"].astype(bool)].copy()

    rows_out = []
    xs = []
    ys = []

    for _, r in use_df.iterrows():
        rr = safe_int(r.get("peak_row", np.nan))
        cc = safe_int(r.get("peak_col", np.nan))
        if rr is None or cc is None:
            continue

        x, y = cf_src.xy(rr, cc)
        row = r.to_dict()

        # Shapefile field names are limited to 10 characters.
        # Full details are preserved in the CSV outputs.
        keep = {
            "name": str(row.get("name", ""))[:80],
            "ptype": str(row.get("profile_type", ""))[:12],
            "side": str(row.get("side", ""))[:12],
            "status": str(row.get("calculation_status", ""))[:40],
            "mode": str(row.get("thickness_mode", ""))[:40],
            "rimtype": str(row.get("rim_type_new", ""))[:20],
            "pk_cf": safe_float(row.get("peak_cf")),
            "thk_dep": safe_float(row.get("thickness_or_depth")),
            "h3": safe_float(row.get("h3")),
            "h3t": safe_float(row.get("h3t")),
            "err_pct": safe_float(row.get("h3_h3t_rel_err_pct")),
            "pass20": int(bool(row.get("h3_h3t_pass20", False))),
            "top_dep": safe_float(row.get("basalt_top_depth")),
            "bot_dep": safe_float(row.get("basalt_bottom_depth")),
            "run_n": safe_float(row.get("basalt_run_count")),
            "gap_n": safe_float(row.get("stop_gap_count")),
            "up_r": safe_float(row.get("upper_boundary_row")),
            "up_c": safe_float(row.get("upper_boundary_col")),
            "lo_r": safe_float(row.get("lower_boundary_row")),
            "lo_c": safe_float(row.get("lower_boundary_col")),
            "ct_r": safe_float(row.get("h_basalt_row")),
            "ct_c": safe_float(row.get("h_basalt_col")),
            "ct2_r": safe_float(row.get("h_basalt_last_row")),
            "ct2_c": safe_float(row.get("h_basalt_last_col")),
            "mid_g": safe_float(row.get("rim_midpoint_global")),
            "filled": int(safe_bool(row.get("crater_filled_flag", False), False)),
            "pfilled": int(safe_bool(row.get("profile_filled_flag", False), False)),
            "unpen": int(safe_bool(row.get("unpenetrated_flag", False), False) or
                         ("unpenetrated" in str(row.get("calculation_status", "")).lower()) or
                         ("unpenetrated" in str(row.get("thickness_mode", "")).lower())),
        }
        rows_out.append(keep)
        xs.append(x)
        ys.append(y)

    if not rows_out:
        print(f"No point records for shapefile output: {out_shp}")
        return

    gdf = gpd.GeoDataFrame(rows_out, geometry=[Point(x, y) for x, y in zip(xs, ys)], crs=cf_src.crs)
    out_shp.parent.mkdir(parents=True, exist_ok=True)
    gdf.to_file(out_shp, driver="ESRI Shapefile", encoding="utf-8")
    print(f"Point SHP saved: {out_shp}")



# ============================================================
# Crater-level robust aggregation of direction-level thickness
# ============================================================
def direction_field_name(profile_type: str, side: str) -> Optional[str]:
    """
    Map the four direction records to original direction fields in the crater-level output.

    row-left  -> row_left
    row-right -> row_right
    col-left  -> col_left
    col-right -> col_right

    Hyphens are avoided because shapefile field names should use underscores.
    """
    p = str(profile_type).lower()
    s = str(side).lower()
    if p == "row" and s == "left":
        return "row_left"
    if p == "row" and s == "right":
        return "row_right"
    if p == "col" and s == "left":
        return "col_left"
    if p == "col" and s == "right":
        return "col_right"
    return None


def aggregate_crater_thickness_values(values,
                                      spread_threshold=RELATIVE_SPREAD_THRESHOLD,
                                      outlier_threshold=REL_DEV_THRESHOLD,
                                      pair_ratio_threshold=PAIR_RATIO_THRESHOLD,
                                      low_ratio_threshold=LOW_RATIO_THRESHOLD,
                                      high_pair_diff_threshold=HIGH_PAIR_DIFF_THRESHOLD,
                                      ge10_threshold=10.0):
    """
    Aggregate 1-4 direction-level thickness estimates into one crater-level value.

    Revised rule: sequential low-tail filtering.

    Rationale
    ---------
    The previous local-consensus rule required two conditions at the same time:
        low_ratio <= 0.477
        high_pair_diff <= 0.569

    This was too conservative for cases such as [79.5, 29.7, 0.7]. The smallest
    value is clearly a low-tail estimate, but the two remaining values are not
    close enough to satisfy high_pair_diff. For crater thickness estimates,
    directional thickness can vary laterally, so the two higher values do not
    have to form a tight pair before a clearly low value is removed.

    Data-driven thresholds
    ----------------------
    pair_ratio_threshold = 0.496
        Derived from Otsu automatic separation of min/max ratios among two-direction
        craters in Thickness.csv.

    low_ratio_threshold = 0.477
        Derived from Otsu automatic separation of low_ratio among multi-direction
        craters in Thickness.csv.

    Rules
    -----
    1) n = 1:
       keep the only valid direction.

    2) n = 2:
       pair_ratio = min(T1,T2) / max(T1,T2).
       If pair_ratio <= 0.496, keep only the larger value.
       Otherwise, average the two values.

    3) n >= 3:
       Compute:
           low_ratio = min_value / median(other directions)

       If low_ratio <= 0.477, remove the minimum value and repeat the check on
       the remaining directions. This allows multiple clearly low directions to
       be removed one after another.

       After low-tail filtering:
         - if two values remain, apply the same pair_ratio rule again;
         - if three or more values remain and no more low-tail value is detected,
           average all remaining values unless the fallback IQR/rel_dev rule is triggered.

    Important
    ---------
    This rule only removes low-tail direction values. It does not remove high
    direction values. In the fallback rule, if the most deviant value is the
    maximum, all values are still kept and averaged.

    Returns
    -------
    final_thickness, used_mask, flag
    """
    vals = np.asarray(values, dtype=float)
    finite = np.isfinite(vals)
    vals_valid = vals[finite]

    used_mask = np.zeros(vals.shape, dtype=bool)
    if vals_valid.size == 0:
        return np.nan, used_mask, "none"

    current_vals = vals_valid.copy()
    current_positions = np.where(finite)[0].copy()
    removed_low_count = 0

    def _rel_spread(arr):
        arr = np.asarray(arr, dtype=float)
        arr = arr[np.isfinite(arr)]
        if arr.size == 0:
            return np.inf
        med = float(np.nanmedian(arr))
        if not np.isfinite(med) or abs(med) < 1e-12:
            return 0.0 if float(np.nanmax(arr) - np.nanmin(arr)) == 0 else np.inf
        return float((np.nanmax(arr) - np.nanmin(arr)) / abs(med))

    def _use_current(flag_name):
        used_mask[current_positions] = True
        return float(np.nanmean(current_vals)), used_mask, flag_name

    while True:
        n = current_vals.size

        # Rule 1: one direction only.
        if n == 1:
            used_mask[current_positions[0]] = True
            if removed_low_count > 0:
                return float(current_vals[0]), used_mask, "rm_low_to_one"
            return float(current_vals[0]), used_mask, "one"

        # Rule 2: two directions. Apply this both for original n=2 and after
        # removing one or more low-tail values from n>=3.
        if n == 2:
            min_val = float(np.nanmin(current_vals))
            max_val = float(np.nanmax(current_vals))
            pair_ratio = min_val / max_val if max_val > 0 else 1.0

            if pair_ratio <= float(pair_ratio_threshold):
                max_pos_in_current = int(np.nanargmax(current_vals))
                used_mask[current_positions[max_pos_in_current]] = True
                if removed_low_count > 0:
                    return float(current_vals[max_pos_in_current]), used_mask, "rm_low_two_keepmax"
                return float(current_vals[max_pos_in_current]), used_mask, "two_keepmax"

            if removed_low_count > 0:
                return _use_current("rm_low_then_two_avg")
            return _use_current("two_avg")

        # Rule 3A: n >= 3. Remove clear low-tail values sequentially.
        min_pos = int(np.nanargmin(current_vals))
        min_val = float(current_vals[min_pos])
        other_vals = np.delete(current_vals, min_pos)
        med_other = float(np.nanmedian(other_vals))

        if np.isfinite(med_other) and abs(med_other) >= 1e-12:
            low_ratio = min_val / abs(med_other)
        else:
            low_ratio = np.inf

        if np.isfinite(low_ratio) and low_ratio <= float(low_ratio_threshold):
            current_vals = np.delete(current_vals, min_pos)
            current_positions = np.delete(current_positions, min_pos)
            removed_low_count += 1
            continue

        # Rule 3B: fallback. If directions are not strongly scattered by the
        # global relative_spread criterion, keep all remaining values.
        if _rel_spread(current_vals) <= float(spread_threshold):
            if removed_low_count > 0:
                return _use_current("rm_low_then_avg")
            return _use_current("avg")

        # Rule 3C: previous leave-one rel_dev fallback for extreme cases.
        rel_dev = np.full(current_vals.shape, np.nan, dtype=float)
        for i in range(current_vals.size):
            others = np.delete(current_vals, i)
            med_other = float(np.nanmedian(others))
            if np.isfinite(med_other) and abs(med_other) >= 1e-12:
                rel_dev[i] = abs(current_vals[i] - med_other) / abs(med_other)

        finite_dev = np.isfinite(rel_dev)
        if not np.any(finite_dev):
            if removed_low_count > 0:
                return _use_current("rm_low_then_avg_nodev")
            return _use_current("avg_nodev")

        worst_pos = int(np.nanargmax(rel_dev))
        worst_dev = float(rel_dev[worst_pos])

        if worst_dev <= float(outlier_threshold):
            if removed_low_count > 0:
                return _use_current("rm_low_then_avg_noout")
            return _use_current("avg_noout")

        worst_val = float(current_vals[worst_pos])
        min_val = float(np.nanmin(current_vals))
        max_val = float(np.nanmax(current_vals))
        tol = 1e-12

        if abs(worst_val - min_val) <= tol:
            current_vals = np.delete(current_vals, worst_pos)
            current_positions = np.delete(current_positions, worst_pos)
            removed_low_count += 1
            continue

        if abs(worst_val - max_val) <= tol:
            if removed_low_count > 0:
                return _use_current("rm_low_then_max_avg")
            return _use_current("max_avg")

        if removed_low_count > 0:
            return _use_current("rm_low_then_mid_avg")
        return _use_current("mid_avg")

def write_crater_summary_shp(direction_df: pd.DataFrame, out_shp: Path, cf_src):
    """
    Write one crater-level shapefile with a compact but useful attribute table.

    Existing direction-level shapefiles are not modified:
      - all_basalt_points.shp
      - basalt_thickness_points.shp

    New output:
      - basalt_thickness_crater_summary.shp

    Fields:
      name       crater name
      final_thk  robust crater-level thickness
      row_right  row-right direction thickness, if available
      col_right  col-right direction thickness, if available
      row_left   row-left direction thickness, if available
      col_left   col-left direction thickness, if available
      n_used     number of directions used to calculate final_thk
      flag       aggregation rule
    """
    if not HAS_GPD:
        print("geopandas/shapely unavailable; skip crater summary shapefile output.")
        return

    if direction_df is None or direction_df.empty:
        print(f"No direction records for crater summary shapefile output: {out_shp}")
        return

    df = direction_df.copy()
    if "h3_h3t_pass20" in df.columns:
        df = df[df["h3_h3t_pass20"].astype(bool)].copy()
    df["_thk"] = pd.to_numeric(df.get("thickness_or_depth", np.nan), errors="coerce")
    df = df[np.isfinite(df["_thk"])].copy()

    if df.empty:
        print(f"No valid thickness records for crater summary shapefile output: {out_shp}")
        return

    rows_out = []
    geoms = []
    direction_order = ["row_right", "col_right", "row_left", "col_left"]

    for name, sub in df.groupby("name", sort=False):
        # Direction fields are left blank if that direction is absent or invalid.
        dir_values = {k: np.nan for k in direction_order}
        dir_rows = {k: [] for k in direction_order}

        for idx, r in sub.iterrows():
            dname = direction_field_name(r.get("profile_type", ""), r.get("side", ""))
            if dname is None:
                continue
            thk = safe_float(r.get("_thk", np.nan))
            if not np.isfinite(thk):
                continue
            dir_rows[dname].append((idx, thk))

        # If duplicate records appear in any direction, average within that direction.
        for dname, items in dir_rows.items():
            if items:
                dir_values[dname] = float(np.nanmean([v for _, v in items]))

        vals = np.array([dir_values[d] for d in direction_order], dtype=float)
        final_thk, used_mask, flag = aggregate_crater_thickness_values(vals)
        if not np.isfinite(final_thk):
            continue

        # Geometry: use crater center when available. If not, use mean peak position
        # from the valid direction records.
        cr = pd.to_numeric(sub.get("center_row", np.nan), errors="coerce")
        cc = pd.to_numeric(sub.get("center_col", np.nan), errors="coerce")
        valid_center = np.isfinite(cr) & np.isfinite(cc)
        if np.any(valid_center):
            rr = int(round(float(cr[valid_center].iloc[0])))
            col = int(round(float(cc[valid_center].iloc[0])))
        else:
            pr = pd.to_numeric(sub.get("peak_row", np.nan), errors="coerce")
            pc = pd.to_numeric(sub.get("peak_col", np.nan), errors="coerce")
            valid_peak = np.isfinite(pr) & np.isfinite(pc)
            if not np.any(valid_peak):
                continue
            rr = int(round(float(np.nanmean(pr[valid_peak]))))
            col = int(round(float(np.nanmean(pc[valid_peak]))))

        if rr < 0 or rr >= cf_src.height or col < 0 or col >= cf_src.width:
            continue

        x, y = cf_src.xy(rr, col)
        rows_out.append({
            "name": str(name)[:80],
            "final_thk": float(final_thk),
            "row_right": safe_float(dir_values["row_right"]),
            "col_right": safe_float(dir_values["col_right"]),
            "row_left": safe_float(dir_values["row_left"]),
            "col_left": safe_float(dir_values["col_left"]),
            "n_used": int(np.sum(used_mask)),
            "flag": str(flag)[:12],
        })
        geoms.append(Point(x, y))

    if not rows_out:
        print(f"No crater summary records for shapefile output: {out_shp}")
        return

    gdf = gpd.GeoDataFrame(rows_out, geometry=geoms, crs=cf_src.crs)
    out_shp.parent.mkdir(parents=True, exist_ok=True)
    gdf.to_file(out_shp, driver="ESRI Shapefile", encoding="utf-8")
    print(f"Crater summary SHP saved: {out_shp}")


def filter_oldmethod_no_h3t_unpenetrated(df: pd.DataFrame) -> Tuple[pd.DataFrame, int]:
    """
    Build the old-method comparison dataset.

    The current main workflow may set thickness_or_depth = h3t for
    unpenetrated basalt profiles, with:
        thickness_source == "h3t_for_unpenetrated_basalt"

    For the extra old-method crater-summary shapefile, these records are
    removed before crater-level aggregation. This does not change the original
    three shapefile outputs.

    Returns
    -------
    filtered_df, removed_count
    """
    if df is None or df.empty:
        return df.copy(), 0

    out = df.copy()
    if "thickness_source" in out.columns:
        source = out["thickness_source"].astype(str).str.lower().str.strip()
        exclude = source.eq(OLDMETHOD_EXCLUDED_THICKNESS_SOURCE.lower())
    else:
        # Fallback for old CSVs without thickness_source.
        mode = out.get("thickness_mode", pd.Series("", index=out.index)).astype(str).str.lower()
        status = out.get("calculation_status", pd.Series("", index=out.index)).astype(str).str.lower()
        unpen = out.get("unpenetrated_flag", pd.Series(False, index=out.index)).apply(lambda v: safe_bool(v, False))
        exclude = (unpen.astype(bool) | mode.str.contains("unpenetrated") | status.str.contains("unpenetrated"))

    removed_count = int(exclude.sum())
    return out.loc[~exclude].copy(), removed_count

def main():
    parser = argparse.ArgumentParser(description="Calculate CE5 basalt thickness from H123 CSV + DEM + CF.")
    parser.add_argument("--dem", default=str(DEFAULT_DEM), help="DEM raster path")
    parser.add_argument("--cf", default=str(DEFAULT_CF), help="CF raster path")
    parser.add_argument("--step1-csv", default=str(DEFAULT_STEP1_CSV), help="CalculateH123.py valid CSV")
    parser.add_argument("--step2-csv", default=str(DEFAULT_STEP2_CSV), help="ExtendCalculateH123.py valid CSV")
    parser.add_argument("--out", default=str(DEFAULT_OUT_DIR), help="Output directory")
    args = parser.parse_args()

    dem_path = Path(args.dem)
    cf_path = Path(args.cf)
    step1_csv = Path(args.step1_csv)
    step2_csv = Path(args.step2_csv)
    out_dir = Path(args.out)
    out_dir.mkdir(parents=True, exist_ok=True)

    if not dem_path.exists():
        raise FileNotFoundError(f"DEM not found: {dem_path}")
    if not cf_path.exists():
        raise FileNotFoundError(f"CF not found: {cf_path}")
    if not step1_csv.exists() and not step2_csv.exists():
        raise FileNotFoundError("Neither step1 nor step2 h123 CSV exists.")

    h123 = combine_h123(step1_csv, step2_csv)

    with rasterio.open(dem_path) as dem_src, rasterio.open(cf_path) as cf_src:
        if dem_src.width != cf_src.width or dem_src.height != cf_src.height:
            print("WARNING: DEM and CF raster sizes differ.")
            print(f"DEM size: {dem_src.height} x {dem_src.width}")
            print(f"CF  size: {cf_src.height} x {cf_src.width}")
            print("The script assumes H123 row/col indices match both rasters. Resample/register CF first if they do not match.")

        profile_diag = build_profile_diagnostics(h123, dem_src, cf_src)

        # Filled flags are inherited from the H123 CSVs. This script does not recalculate
        # the filled-crater slope criterion. From this version onward filled flags are
        # diagnostic only; they DO NOT exclude records from thickness calculation.
        crater_filled = {}
        for name, sub in h123.groupby("name", sort=False):
            flags = []
            for key, info in profile_diag.items():
                if key[0] == name:
                    flags.append(bool(info.get("crater_filled_flag_from_csv", False)))
                    flags.append(bool(info.get("profile_filled_flag", False)))
            crater_filled[name] = any(flags)

        records = []
        for _, rec in h123.iterrows():
            pkey = profile_key(rec)
            pinfo = profile_diag.get(pkey, {})
            cflag = bool(crater_filled.get(str(rec["name"]), False))
            records.append(calculate_direction_record(dem_src, cf_src, rec, pinfo, cflag))

        out_df = pd.DataFrame(records)
        out_df = attach_felsic_felsic_profile_thickness(out_df)
        out_df = attach_h3_h3t_relative_error(out_df)

        annotated_csv = out_dir / "h123_with_filled_and_basalt_flags.csv"
        thickness_csv = out_dir / "basalt_thickness_direction_records.csv"
        summary_csv = out_dir / "basalt_thickness_crater_profile_summary.csv"
        all_shp = out_dir / "all_basalt_points.shp"
        filtered_shp = out_dir / "basalt_thickness_points.shp"
        crater_summary_shp = out_dir / "basalt_thickness_crater_summary.shp"
        oldmethod_crater_summary_shp = out_dir / "basalt_thickness_crater_summary_oldmethod.shp"
        oldmethod_direction_csv = out_dir / "basalt_thickness_direction_records_oldmethod_no_h3t.csv"

        out_df.to_csv(thickness_csv, index=False, encoding="utf-8-sig")

        # Annotated H123-like table, useful for checking which records were excluded.
        flag_cols = [
            "name", "profile_type", "side", "source_step", "reason",
            "crater_filled_flag", "profile_filled_flag", "filled_slope_ratio_le1",
            "profile_basalt_only_unpenetrated", "profile_all_between_basalt",
            "peak_cf", "rim_type_new", "calculation_status", "thickness_mode",
            "h1", "h2", "h3", "h3t", "h3_h3t_rel_err_pct", "h3_h3t_pass20",
            "left_peak_global", "right_peak_global", "rim_midpoint_global", "midpoint_source",
            "search_end_global", "search_valid_count", "search_basalt_count", "search_nonbasalt_count",
            "basalt_run_first_idx", "basalt_run_last_idx", "basalt_run_count",
            "stop_gap_first_idx", "stop_gap_count", "max_nonbasalt_gap_allowed",
            "upper_boundary_idx", "upper_boundary_elev", "upper_boundary_row", "upper_boundary_col", "upper_boundary_cf",
            "lower_boundary_idx", "lower_boundary_elev", "lower_boundary_row", "lower_boundary_col", "lower_boundary_cf",
            "h2_basalt", "h2_basalt_top", "h2_basalt_bottom",
            "basalt_top_depth", "basalt_bottom_depth", "thickness_or_depth", "profile_t_basalt",
            "peak_row", "peak_col", "bottom_row", "bottom_col",
            "h_basalt_row", "h_basalt_col", "h_basalt_cf",
            "h_basalt_last_row", "h_basalt_last_col", "h_basalt_last_cf",
            "cf_class", "thk_ok", "unpenetrated_flag", "thickness_source",
            "contact_note"
        ]
        for c in flag_cols:
            if c not in out_df.columns:
                out_df[c] = np.nan
        out_df[flag_cols].to_csv(annotated_csv, index=False, encoding="utf-8-sig")

        # Profile-level summary.
        summary_rows = []
        for (name, profile_type), sub in out_df.groupby(["name", "profile_type"], sort=False):
            first = sub.iloc[0]
            summary_rows.append({
                "name": name,
                "profile_type": profile_type,
                "crater_filled_flag": bool(first.get("crater_filled_flag", False)),
                "profile_filled_flag": bool(first.get("profile_filled_flag", False)),
                "filled_slope_ratio_le1": safe_float(first.get("filled_slope_ratio_le1")),
                "profile_basalt_only_unpenetrated": bool(first.get("profile_basalt_only_unpenetrated", False)),
                "left_status": str(sub[sub["side"].eq("left")]["calculation_status"].iloc[0]) if np.any(sub["side"].eq("left")) else "",
                "right_status": str(sub[sub["side"].eq("right")]["calculation_status"].iloc[0]) if np.any(sub["side"].eq("right")) else "",
                "left_mode": str(sub[sub["side"].eq("left")]["thickness_mode"].iloc[0]) if np.any(sub["side"].eq("left")) else "",
                "right_mode": str(sub[sub["side"].eq("right")]["thickness_mode"].iloc[0]) if np.any(sub["side"].eq("right")) else "",
                "profile_t_basalt": safe_float(first.get("profile_t_basalt")),
                "profile_t_basalt_status": str(first.get("profile_t_basalt_status", "")),
            })
        pd.DataFrame(summary_rows).to_csv(summary_csv, index=False, encoding="utf-8-sig")

        write_point_shp(out_df, all_shp, cf_src, only_pass20=False)
        filtered_df = out_df[out_df["h3_h3t_pass20"].astype(bool)].copy()
        write_point_shp(out_df, filtered_shp, cf_src, only_pass20=True)
        write_crater_summary_shp(filtered_df, crater_summary_shp, cf_src)

        if WRITE_OLDMETHOD_NO_H3T_UNPENETRATED_SUMMARY:
            oldmethod_filtered_df, oldmethod_removed_n = filter_oldmethod_no_h3t_unpenetrated(filtered_df)
            oldmethod_filtered_df.to_csv(oldmethod_direction_csv, index=False, encoding="utf-8-sig")
            write_crater_summary_shp(oldmethod_filtered_df, oldmethod_crater_summary_shp, cf_src)
        else:
            oldmethod_filtered_df = filtered_df.copy()
            oldmethod_removed_n = 0

        fit_info = fit_h3_vs_h3t_r2(filtered_df)
        print("\n========== h3 vs h3t filter summary ==========")
        print("Relative error formula: abs(h3 - h3t) / ((h3 + h3t) / 2)")
        print("Filter rule: keep true thk_dep not NULL and relative error < 20%; remove relative error >= 20%")
        print(f"All direction records: {len(out_df)}")
        print(f"Kept direction records: {len(filtered_df)}")
        print(f"Removed direction records: {len(out_df) - len(filtered_df)}")
        print(f"Filtered fit: h3 = {fit_info['slope']:.6f} * h3t + {fit_info['intercept']:.6f}")
        print(f"Filtered R2: {fit_info['r2']:.6f}  (n = {fit_info['n']})")
        if WRITE_OLDMETHOD_NO_H3T_UNPENETRATED_SUMMARY:
            print("\n========== old-method no-H3T-unpenetrated summary ==========")
            print(f"Removed H3T-derived unpenetrated direction records: {oldmethod_removed_n}")
            print(f"Remaining direction records for old-method summary: {len(oldmethod_filtered_df)}")
            print(f"Old-method crater summary SHP: {oldmethod_crater_summary_shp}")
            print("==========================================================")
        print("=============================================\n")

    print(f"Annotated CSV saved: {annotated_csv}")
    print(f"Thickness direction CSV saved: {thickness_csv}")
    print(f"Profile summary CSV saved: {summary_csv}")
    print(f"All point SHP saved: {all_shp}")
    print(f"Filtered thickness SHP saved: {filtered_shp}")
    print(f"Crater summary SHP saved: {crater_summary_shp}")
    if WRITE_OLDMETHOD_NO_H3T_UNPENETRATED_SUMMARY:
        print(f"Old-method no-H3T crater summary SHP saved: {oldmethod_crater_summary_shp}")
        print(f"Old-method direction CSV saved: {oldmethod_direction_csv}")
    print("Done.")


if __name__ == "__main__":
    main()
