# -*- coding: utf-8 -*-
"""
CalculateBasaltThickness.py

Purpose
-------
Use the h1/h2/h3/h3t results from CalculateH123.py step1 and ExtendCalculateH123.py step2
to calculate CE5-area basalt thickness or burial depth from DEM + CF rasters.

Main updates relative to the old CalculateUnitPixel.py
------------------------------------------------------
1. Basalt is defined as CF > 8.2, not CF < 8.2.
2. Rim type is judged only by the exact CF value at peak_row/peak_col, not by a local median window.
3. Filled crater filtering is NOT recalculated here. This script only reads
   profile_filled_flag / crater_filled_flag from the H123 CSV generated by
   CalculateH123.py and ExtendCalculateH123.py.
4. Unpenetrated basalt case is added:
   if both rims are basalt and all valid pixels between the two rims are basalt, the crater/profile
   is marked as basalt_only_unpenetrated and no thickness is calculated.
5. The script writes annotated CSV outputs and an optional point shapefile.

Expected inputs
---------------
- DEM raster: Database/CE5/CE5_dem.tif
- CF raster : Database/CE5/CE5_CF.tif
- Step1 CSV : Database/CE5/yolo/chickin/step1/all_yolo_h123.csv
- Step2 CSV : Database/CE5/yolo/chickin/step2/all_yolo_h123.csv

Example
-------
python scripts/CalculateBasaltThickness.py ^
  --dem Database/CE5/CE5_dem.tif ^
  --cf Database/CE5/CE5_CF.tif ^
  --step1-csv Database/CE5/yolo/chickin/step1/all_yolo_h123.csv ^
  --step2-csv Database/CE5/yolo/chickin/step2/all_yolo_h123.csv ^
  --out Database/CE5/yolo/chickin/basalt_thickness
"""

import argparse
import math
from pathlib import Path
from typing import Dict, List, Optional, Tuple

import numpy as np
import pandas as pd
import rasterio
from rasterio.windows import Window
from rasterio.transform import xy

try:
    import geopandas as gpd
    from shapely.geometry import Point
    HAS_GPD = True
except Exception:
    HAS_GPD = False


# ============================================================
# USER CONFIGURATION: edit paths and core thresholds here
# ============================================================
# Input rasters
DEFAULT_DEM = Path(r"Database/CE5/CE5_dem.tif")
DEFAULT_CF = Path(r"Database/CE5/CE5_CF.tif")

# H123 result CSVs generated before this script
# step1: output from CalculateH123.py
# step2: output from ExtendCalculateH123.py
DEFAULT_STEP1_CSV = Path(r"Database/CE5/yolo/chickin/step1/all_yolo_h123.csv")
DEFAULT_STEP2_CSV = Path(r"Database/CE5/yolo/chickin/step2/all_yolo_h123.csv")

# Output folder for basalt thickness results
DEFAULT_OUT_DIR = Path(r"Database/CE5/yolo/chickin/basalt_thickness")

# Basalt criterion. In this project, CF > 8.2 is treated as basalt.
BASALT_CF_THRESHOLD = 8.2

# Invalid raster value handling
INVALID_LOW = -3e10
MOON_RADIUS_M = 1737400.0

# Filled-crater flags are inherited from H123 CSVs.
# This script does NOT recalculate filled craters.
# Required CSV fields if filled filtering is needed:
#   profile_filled_flag, crater_filled_flag

# -----------------------------
# Basic utilities
# -----------------------------
def clean_values(values, invalid_low=INVALID_LOW, invalid_zero=False):
    arr = np.asarray(values, dtype=float).copy()
    arr[~np.isfinite(arr)] = np.nan
    arr[arr < invalid_low] = np.nan
    if invalid_zero:
        arr[arr == 0] = np.nan
    return arr


def safe_float(v, default=np.nan):
    try:
        if pd.isna(v):
            return default
        return float(v)
    except Exception:
        return default


def safe_int(v) -> Optional[int]:
    try:
        if pd.isna(v):
            return None
        vv = float(v)
        if not np.isfinite(vv):
            return None
        return int(round(vv))
    except Exception:
        return None


def safe_bool(v, default=False) -> bool:
    if v is None:
        return bool(default)
    try:
        if pd.isna(v):
            return bool(default)
    except Exception:
        pass
    if isinstance(v, str):
        s = v.strip().lower()
        if s in ("1", "true", "yes", "y", "filled", "是"):
            return True
        if s in ("0", "false", "no", "n", "not_filled", "否", ""):
            return False
    try:
        return bool(float(v) != 0)
    except Exception:
        return bool(default)


def moon_distance_m(lon1, lat1, lon2, lat2, radius=MOON_RADIUS_M):
    lon1 = np.radians(lon1)
    lat1 = np.radians(lat1)
    lon2 = np.radians(lon2)
    lat2 = np.radians(lat2)
    dlon = lon2 - lon1
    dlat = lat2 - lat1
    a = np.sin(dlat / 2.0) ** 2 + np.cos(lat1) * np.cos(lat2) * np.sin(dlon / 2.0) ** 2
    c = 2.0 * np.arctan2(np.sqrt(a), np.sqrt(1.0 - a))
    return radius * c


def raster_is_geographic(src) -> bool:
    if src.crs is None:
        return True
    txt = str(src.crs).lower()
    return ("degree" in txt) or ("geogcs" in txt) or ("longlat" in txt) or ("4326" in txt)


def point_distance_from_coords(x1, y1, x2, y2, is_geo=True):
    if is_geo:
        return moon_distance_m(x1, y1, x2, y2)
    return float(math.hypot(x2 - x1, y2 - y1))


def read_h123_csv(path: Path, source_step: str) -> pd.DataFrame:
    if path is None or not path.exists():
        return pd.DataFrame()

    df = pd.read_csv(path, encoding="utf-8-sig", dtype={"name": str})
    df["source_step"] = source_step

    # Normalize required columns.
    required = [
        "name", "profile_type", "side", "reason",
        "peak_val", "outer_mean", "bottom_elev",
        "h1", "h2", "h3", "h3t",
        "line_dem_row", "line_dem_col",
        "center_row", "center_col",
        "peak_row", "peak_col",
        "bottom_row", "bottom_col",
        "peak_global", "bottom_global"
    ]
    for c in required:
        if c not in df.columns:
            df[c] = np.nan

    # Keep only valid h123 records by default.
    if "reason" in df.columns:
        df = df[df["reason"].astype(str).str.lower().eq("ok")].copy()

    df["profile_type"] = df["profile_type"].astype(str).str.lower()
    df["side"] = df["side"].astype(str).str.lower()
    return df


def combine_h123(step1_csv: Path, step2_csv: Path) -> pd.DataFrame:
    dfs = []
    s1 = read_h123_csv(step1_csv, "step1")
    s2 = read_h123_csv(step2_csv, "step2")
    if not s1.empty:
        dfs.append(s1)
    if not s2.empty:
        dfs.append(s2)

    if not dfs:
        raise FileNotFoundError("No valid step1/step2 h123 CSV records were loaded.")

    df = pd.concat(dfs, ignore_index=True)

    # If duplicates exist, prefer step2 because it is usually a remedial calculation.
    df["_source_priority"] = df["source_step"].map({"step1": 1, "step2": 2}).fillna(0)
    df = df.sort_values(["name", "profile_type", "side", "_source_priority"])
    df = df.drop_duplicates(subset=["name", "profile_type", "side"], keep="last").copy()
    df = df.drop(columns=["_source_priority"])
    return df


def read_profile_segment(src, profile_type: str, fixed_index: int, start_global: int, end_global: int):
    """
    Read a row or column segment from a raster. Returns values, rows, cols.
    start_global/end_global are DEM row indices for col profiles and DEM col indices for row profiles.
    """
    start_global = int(start_global)
    end_global = int(end_global)
    lo = min(start_global, end_global)
    hi = max(start_global, end_global)

    if profile_type == "row":
        row = int(fixed_index)
        if row < 0 or row >= src.height:
            return np.array([]), np.array([], dtype=int), np.array([], dtype=int)
        lo = max(0, lo)
        hi = min(src.width - 1, hi)
        if hi < lo:
            return np.array([]), np.array([], dtype=int), np.array([], dtype=int)
        arr = src.read(1, window=Window(lo, row, hi - lo + 1, 1))[0, :]
        cols = np.arange(lo, hi + 1, dtype=int)
        rows = np.full(cols.shape, row, dtype=int)
    else:
        col = int(fixed_index)
        if col < 0 or col >= src.width:
            return np.array([]), np.array([], dtype=int), np.array([], dtype=int)
        lo = max(0, lo)
        hi = min(src.height - 1, hi)
        if hi < lo:
            return np.array([]), np.array([], dtype=int), np.array([], dtype=int)
        arr = src.read(1, window=Window(col, lo, 1, hi - lo + 1))[:, 0]
        rows = np.arange(lo, hi + 1, dtype=int)
        cols = np.full(rows.shape, col, dtype=int)

    arr = clean_values(arr, invalid_low=INVALID_LOW, invalid_zero=False)

    # Preserve requested direction.
    if start_global > end_global:
        arr = arr[::-1]
        rows = rows[::-1]
        cols = cols[::-1]

    return arr, rows, cols


def get_raster_value(src, row: int, col: int) -> float:
    if row is None or col is None:
        return np.nan
    row = int(row)
    col = int(col)
    if row < 0 or row >= src.height or col < 0 or col >= src.width:
        return np.nan
    val = src.read(1, window=Window(col, row, 1, 1))[0, 0]
    val = clean_values([val], invalid_low=INVALID_LOW, invalid_zero=False)[0]
    return float(val) if np.isfinite(val) else np.nan


def index_global_for_record(rec: pd.Series) -> Optional[int]:
    profile_type = str(rec.get("profile_type", "")).lower()
    if profile_type == "row":
        return safe_int(rec.get("peak_col", np.nan))
    if profile_type == "col":
        return safe_int(rec.get("peak_row", np.nan))
    return None


def fixed_index_for_record(rec: pd.Series) -> Optional[int]:
    profile_type = str(rec.get("profile_type", "")).lower()
    if profile_type == "row":
        return safe_int(rec.get("line_dem_row", rec.get("peak_row", np.nan)))
    if profile_type == "col":
        return safe_int(rec.get("line_dem_col", rec.get("peak_col", np.nan)))
    return None


def bottom_global_for_record(rec: pd.Series) -> Optional[int]:
    profile_type = str(rec.get("profile_type", "")).lower()
    if profile_type == "row":
        return safe_int(rec.get("bottom_col", np.nan))
    if profile_type == "col":
        return safe_int(rec.get("bottom_row", np.nan))
    return None


def adjacent_slope_ratio_le_threshold(dem_src, dem_vals, rows, cols, threshold_deg=1.0):
    dem_vals = clean_values(dem_vals, invalid_low=INVALID_LOW, invalid_zero=False)
    if len(dem_vals) < 2:
        return np.nan, 0, 0

    xs, ys = xy(dem_src.transform, rows, cols, offset="center")
    xs = np.asarray(xs, dtype=float)
    ys = np.asarray(ys, dtype=float)
    is_geo = raster_is_geographic(dem_src)

    slopes = []
    for i in range(len(dem_vals) - 1):
        z1 = dem_vals[i]
        z2 = dem_vals[i + 1]
        if not (np.isfinite(z1) and np.isfinite(z2)):
            continue
        dist = point_distance_from_coords(xs[i], ys[i], xs[i + 1], ys[i + 1], is_geo=is_geo)
        if not np.isfinite(dist) or dist <= 0:
            continue
        slopes.append(abs(math.degrees(math.atan((z2 - z1) / dist))))

    if not slopes:
        return np.nan, 0, 0

    slopes = np.asarray(slopes, dtype=float)
    le_count = int(np.sum(slopes <= threshold_deg))
    valid_count = int(slopes.size)
    return float(le_count / valid_count), le_count, valid_count


def profile_key(rec: pd.Series):
    return (str(rec.get("name")), str(rec.get("profile_type")).lower())


def build_profile_diagnostics(df: pd.DataFrame, dem_src, cf_src) -> Dict[Tuple[str, str], Dict]:
    """
    For each crater + profile_type, this function only reads filled flags from the H123 CSV
    and calculates the CF-based unpenetrated-basalt diagnostic. It does NOT recalculate the
    filled-crater slope criterion here.
    """
    diag: Dict[Tuple[str, str], Dict] = {}

    for key, sub in df.groupby(["name", "profile_type"], sort=False):
        name, profile_type = key
        left = sub[sub["side"].eq("left")]
        right = sub[sub["side"].eq("right")]

        profile_filled_flag = False
        crater_filled_flag = False
        filled_ratio_vals = []
        filled_le_count_vals = []
        filled_valid_count_vals = []

        for _, r in sub.iterrows():
            profile_filled_flag = profile_filled_flag or safe_bool(r.get("profile_filled_flag", False), False)
            crater_filled_flag = crater_filled_flag or safe_bool(r.get("crater_filled_flag", False), False)
            rv = safe_float(r.get("filled_slope_ratio_le1", np.nan))
            if np.isfinite(rv):
                filled_ratio_vals.append(rv)
            le = safe_float(r.get("filled_slope_le1_count", np.nan))
            vc = safe_float(r.get("filled_slope_valid_count", np.nan))
            if np.isfinite(le):
                filled_le_count_vals.append(int(le))
            if np.isfinite(vc):
                filled_valid_count_vals.append(int(vc))

        info = {
            "name": name,
            "profile_type": profile_type,
            "profile_has_two_rims": False,
            "filled_slope_ratio_le1": float(np.nanmax(filled_ratio_vals)) if filled_ratio_vals else np.nan,
            "filled_slope_le1_count": int(max(filled_le_count_vals)) if filled_le_count_vals else 0,
            "filled_slope_valid_count": int(max(filled_valid_count_vals)) if filled_valid_count_vals else 0,
            "profile_filled_flag": bool(profile_filled_flag),
            "crater_filled_flag_from_csv": bool(crater_filled_flag),
            "profile_between_valid_cf_count": 0,
            "profile_between_basalt_count": 0,
            "profile_between_nonbasalt_count": 0,
            "profile_all_between_basalt": False,
            "profile_both_rims_basalt": False,
            "profile_basalt_only_unpenetrated": False,
        }

        if left.empty or right.empty:
            diag[key] = info
            continue

        left_rec = left.iloc[0]
        right_rec = right.iloc[0]

        fixed = fixed_index_for_record(left_rec)
        left_peak_g = index_global_for_record(left_rec)
        right_peak_g = index_global_for_record(right_rec)
        if fixed is None or left_peak_g is None or right_peak_g is None:
            diag[key] = info
            continue

        start_g = min(left_peak_g, right_peak_g)
        end_g = max(left_peak_g, right_peak_g)

        cf_vals, _, _ = read_profile_segment(cf_src, profile_type, fixed, start_g, end_g)
        info["profile_has_two_rims"] = True

        cf_vals = clean_values(cf_vals, invalid_low=INVALID_LOW, invalid_zero=False)
        valid_cf = cf_vals[np.isfinite(cf_vals)]
        basalt_mask = valid_cf > BASALT_CF_THRESHOLD
        info["profile_between_valid_cf_count"] = int(valid_cf.size)
        info["profile_between_basalt_count"] = int(np.sum(basalt_mask)) if valid_cf.size else 0
        info["profile_between_nonbasalt_count"] = int(np.sum(~basalt_mask)) if valid_cf.size else 0
        info["profile_all_between_basalt"] = bool(valid_cf.size > 0 and np.all(basalt_mask))

        left_cf = get_raster_value(cf_src, safe_int(left_rec.get("peak_row")), safe_int(left_rec.get("peak_col")))
        right_cf = get_raster_value(cf_src, safe_int(right_rec.get("peak_row")), safe_int(right_rec.get("peak_col")))
        info["left_peak_cf"] = left_cf
        info["right_peak_cf"] = right_cf
        info["profile_both_rims_basalt"] = bool(np.isfinite(left_cf) and np.isfinite(right_cf) and
                                                left_cf > BASALT_CF_THRESHOLD and right_cf > BASALT_CF_THRESHOLD)

        info["profile_basalt_only_unpenetrated"] = bool(
            info["profile_both_rims_basalt"] and info["profile_all_between_basalt"]
        )

        diag[key] = info

    return diag


def sample_peak_to_bottom(dem_src, cf_src, rec: pd.Series):
    profile_type = str(rec["profile_type"]).lower()
    fixed = fixed_index_for_record(rec)
    peak_g = index_global_for_record(rec)
    bottom_g = bottom_global_for_record(rec)

    if fixed is None or peak_g is None or bottom_g is None:
        return None

    dem_vals, rows, cols = read_profile_segment(dem_src, profile_type, fixed, peak_g, bottom_g)
    cf_vals, _, _ = read_profile_segment(cf_src, profile_type, fixed, peak_g, bottom_g)

    if len(dem_vals) == 0 or len(cf_vals) == 0:
        return None

    n = min(len(dem_vals), len(cf_vals))
    return dem_vals[:n], cf_vals[:n], rows[:n], cols[:n]


def calculate_direction_record(dem_src, cf_src, rec: pd.Series, profile_info: Dict, crater_filled_flag: bool) -> Dict:
    name = str(rec["name"])
    profile_type = str(rec["profile_type"]).lower()
    side = str(rec["side"]).lower()

    peak_row = safe_int(rec.get("peak_row"))
    peak_col = safe_int(rec.get("peak_col"))
    bottom_row = safe_int(rec.get("bottom_row"))
    bottom_col = safe_int(rec.get("bottom_col"))

    h1 = safe_float(rec.get("h1"))
    peak_val = safe_float(rec.get("peak_val"))
    old_h2_bottom = safe_float(rec.get("h2"))

    peak_cf = get_raster_value(cf_src, peak_row, peak_col)
    rim_type = "unknown"
    if np.isfinite(peak_cf):
        rim_type = "basalt_rim" if peak_cf > BASALT_CF_THRESHOLD else "nonbasalt_rim"

    out = rec.to_dict()
    out.update({
        "peak_cf": peak_cf,
        "basalt_threshold_rule": f"CF>{BASALT_CF_THRESHOLD}",
        "rim_type_new": rim_type,
        "filled_slope_ratio_le1": profile_info.get("filled_slope_ratio_le1", np.nan),
        "filled_slope_le1_count": profile_info.get("filled_slope_le1_count", 0),
        "filled_slope_valid_count": profile_info.get("filled_slope_valid_count", 0),
        "profile_filled_flag": bool(profile_info.get("profile_filled_flag", False)),
        "crater_filled_flag": bool(crater_filled_flag),
        "profile_basalt_only_unpenetrated": bool(profile_info.get("profile_basalt_only_unpenetrated", False)),
        "profile_all_between_basalt": bool(profile_info.get("profile_all_between_basalt", False)),
        "profile_between_valid_cf_count": profile_info.get("profile_between_valid_cf_count", 0),
        "profile_between_basalt_count": profile_info.get("profile_between_basalt_count", 0),
        "profile_between_nonbasalt_count": profile_info.get("profile_between_nonbasalt_count", 0),
        "h_basalt_elev": np.nan,
        "h_basalt_row": np.nan,
        "h_basalt_col": np.nan,
        "h2_basalt": np.nan,
        "thickness_or_depth": np.nan,
        "thickness_mode": "not_calculated",
        "calculation_status": "not_started",
        "contact_idx_in_peak_to_bottom": np.nan,
        "contact_cf": np.nan,
        "contact_note": "",
        "old_h2_to_bottom": old_h2_bottom,
    })

    # Exclusion 1: filled crater/profile
    if crater_filled_flag:
        out["calculation_status"] = "excluded_filled_crater"
        out["thickness_mode"] = "filled_crater_no_cf_calculation"
        return out

    # Exclusion 2: basalt rim but no penetration; only basalt between the two rims.
    if bool(profile_info.get("profile_basalt_only_unpenetrated", False)):
        out["calculation_status"] = "excluded_basalt_only_unpenetrated"
        out["thickness_mode"] = "basalt_rim_all_between_rims_basalt_no_thickness"
        return out

    if rim_type == "unknown":
        out["calculation_status"] = "invalid_peak_cf"
        return out

    if not (np.isfinite(h1) and np.isfinite(peak_val)):
        out["calculation_status"] = "invalid_h1_or_peak_val"
        return out

    sampled = sample_peak_to_bottom(dem_src, cf_src, rec)
    if sampled is None:
        out["calculation_status"] = "invalid_peak_to_bottom_profile"
        return out

    dem_vals, cf_vals, rows, cols = sampled
    dem_vals = clean_values(dem_vals, invalid_low=INVALID_LOW, invalid_zero=False)
    cf_vals = clean_values(cf_vals, invalid_low=INVALID_LOW, invalid_zero=False)

    valid = np.isfinite(dem_vals) & np.isfinite(cf_vals)
    if np.sum(valid) == 0:
        out["calculation_status"] = "no_valid_peak_to_bottom_values"
        return out

    basalt_mask = valid & (cf_vals > BASALT_CF_THRESHOLD)

    if rim_type == "basalt_rim":
        # Find the first non-basalt pixel after the basalt rim along the inward profile.
        # This implements the "next pixel after the last basalt pixel" contact rule.
        first_nonbasalt = None
        for i in range(1, len(cf_vals)):
            if not valid[i]:
                continue
            if cf_vals[i] <= BASALT_CF_THRESHOLD:
                first_nonbasalt = i
                break

        if first_nonbasalt is None:
            out["calculation_status"] = "basalt_rim_no_nonbasalt_contact_before_bottom"
            out["thickness_mode"] = "basalt_rim_contact_not_found"
            return out

        contact_i = int(first_nonbasalt)
        h_basalt_elev = float(dem_vals[contact_i])
        h2_basalt = float(peak_val - h_basalt_elev)
        thickness = float(0.8 * (h2_basalt - 0.2 * h1))

        out.update({
            "h_basalt_elev": h_basalt_elev,
            "h_basalt_row": int(rows[contact_i]),
            "h_basalt_col": int(cols[contact_i]),
            "h2_basalt": h2_basalt,
            "thickness_or_depth": thickness if thickness >= 0 else np.nan,
            "thickness_mode": "basalt_rim_thickness",
            "calculation_status": "ok" if thickness >= 0 else "negative_result_set_nan",
            "contact_idx_in_peak_to_bottom": contact_i,
            "contact_cf": float(cf_vals[contact_i]),
            "contact_note": "first non-basalt pixel after basalt rim; equivalent to next pixel after last basalt pixel",
        })
        return out

    # nonbasalt rim: find the first basalt pixel from rim inward.
    first_basalt = None
    for i in range(1, len(cf_vals)):
        if basalt_mask[i]:
            first_basalt = i
            break

    if first_basalt is None:
        out["calculation_status"] = "no_basalt_detected_from_rim_to_bottom"
        out["thickness_mode"] = "no_basalt_detected"
        return out

    contact_i = int(first_basalt)
    h_basalt_elev = float(dem_vals[contact_i])
    h2_basalt = float(peak_val - h_basalt_elev)
    burial_depth = float(0.8 * (h2_basalt - 0.2 * h1))

    out.update({
        "h_basalt_elev": h_basalt_elev,
        "h_basalt_row": int(rows[contact_i]),
        "h_basalt_col": int(cols[contact_i]),
        "h2_basalt": h2_basalt,
        "thickness_or_depth": burial_depth if burial_depth >= 0 else np.nan,
        "thickness_mode": "nonbasalt_rim_burial_depth",
        "calculation_status": "ok" if burial_depth >= 0 else "negative_result_set_nan",
        "contact_idx_in_peak_to_bottom": contact_i,
        "contact_cf": float(cf_vals[contact_i]),
        "contact_note": "first basalt pixel from non-basalt rim inward",
    })
    return out


def attach_felsic_felsic_profile_thickness(records_df: pd.DataFrame) -> pd.DataFrame:
    """
    If both left and right directions of the same name+profile are nonbasalt-rim burial-depth cases,
    calculate profile true thickness as abs(depth_right - depth_left).

    This follows the old CalculateUnitPixel.py logic but makes the two-step formula explicit:
      h_begin = 0.8 * ((Hrim_left - Hbasalt_left) - 0.2*h1_left)
      h_end   = 0.8 * ((Hrim_right - Hbasalt_right) - 0.2*h1_right)
      t_basalt = abs(h_end - h_begin)
    """
    df = records_df.copy()
    df["profile_t_basalt"] = np.nan
    df["profile_t_basalt_status"] = ""

    for key, sub in df.groupby(["name", "profile_type"], sort=False):
        left = sub[sub["side"].eq("left")]
        right = sub[sub["side"].eq("right")]
        if left.empty or right.empty:
            continue

        li = left.index[0]
        ri = right.index[0]
        left_mode = str(df.loc[li, "thickness_mode"])
        right_mode = str(df.loc[ri, "thickness_mode"])

        if left_mode == "nonbasalt_rim_burial_depth" and right_mode == "nonbasalt_rim_burial_depth":
            dl = safe_float(df.loc[li, "thickness_or_depth"])
            dr = safe_float(df.loc[ri, "thickness_or_depth"])
            if np.isfinite(dl) and np.isfinite(dr):
                t = abs(dr - dl)
                df.loc[[li, ri], "profile_t_basalt"] = t
                df.loc[[li, ri], "profile_t_basalt_status"] = "felsic_felsic_true_thickness_from_depth_difference"
            else:
                df.loc[[li, ri], "profile_t_basalt_status"] = "felsic_felsic_but_invalid_depth"
    return df


def write_point_shp(df: pd.DataFrame, out_shp: Path, cf_src):
    if not HAS_GPD:
        print("geopandas/shapely unavailable; skip shapefile output.")
        return

    rows = []
    xs = []
    ys = []

    for _, r in df.iterrows():
        rr = safe_int(r.get("h_basalt_row", np.nan))
        cc = safe_int(r.get("h_basalt_col", np.nan))
        if rr is None or cc is None:
            rr = safe_int(r.get("peak_row", np.nan))
            cc = safe_int(r.get("peak_col", np.nan))
        if rr is None or cc is None:
            continue

        x, y = cf_src.xy(rr, cc)
        row = r.to_dict()

        # Shapefile field names are limited; write the full CSV as authoritative.
        keep = {
            "name": str(row.get("name", "")),
            "ptype": str(row.get("profile_type", "")),
            "side": str(row.get("side", "")),
            "status": str(row.get("calculation_status", ""))[:40],
            "mode": str(row.get("thickness_mode", ""))[:40],
            "rimtype": str(row.get("rim_type_new", ""))[:20],
            "pk_cf": safe_float(row.get("peak_cf")),
            "thk_dep": safe_float(row.get("thickness_or_depth")),
            "t_prof": safe_float(row.get("profile_t_basalt")),
            "filled": int(bool(row.get("crater_filled_flag", False))),
            "unpen": int(bool(row.get("profile_basalt_only_unpenetrated", False))),
        }
        rows.append(keep)
        xs.append(x)
        ys.append(y)

    if not rows:
        print("No point records for shapefile output.")
        return

    gdf = gpd.GeoDataFrame(rows, geometry=[Point(x, y) for x, y in zip(xs, ys)], crs=cf_src.crs)
    out_shp.parent.mkdir(parents=True, exist_ok=True)
    gdf.to_file(out_shp, driver="ESRI Shapefile", encoding="utf-8")
    print(f"Point SHP saved: {out_shp}")


def main():
    parser = argparse.ArgumentParser(description="Calculate CE5 basalt thickness from H123 CSV + DEM + CF.")
    parser.add_argument("--dem", default=str(DEFAULT_DEM), help="DEM raster path")
    parser.add_argument("--cf", default=str(DEFAULT_CF), help="CF raster path")
    parser.add_argument("--step1-csv", default=str(DEFAULT_STEP1_CSV), help="CalculateH123.py valid CSV")
    parser.add_argument("--step2-csv", default=str(DEFAULT_STEP2_CSV), help="ExtendCalculateH123.py valid CSV")
    parser.add_argument("--out", default=str(DEFAULT_OUT_DIR), help="Output directory")
    args = parser.parse_args()

    dem_path = Path(args.dem)
    cf_path = Path(args.cf)
    step1_csv = Path(args.step1_csv)
    step2_csv = Path(args.step2_csv)
    out_dir = Path(args.out)
    out_dir.mkdir(parents=True, exist_ok=True)

    if not dem_path.exists():
        raise FileNotFoundError(f"DEM not found: {dem_path}")
    if not cf_path.exists():
        raise FileNotFoundError(f"CF not found: {cf_path}")
    if not step1_csv.exists() and not step2_csv.exists():
        raise FileNotFoundError("Neither step1 nor step2 h123 CSV exists.")

    h123 = combine_h123(step1_csv, step2_csv)

    with rasterio.open(dem_path) as dem_src, rasterio.open(cf_path) as cf_src:
        if dem_src.width != cf_src.width or dem_src.height != cf_src.height:
            print("WARNING: DEM and CF raster sizes differ.")
            print(f"DEM size: {dem_src.height} x {dem_src.width}")
            print(f"CF  size: {cf_src.height} x {cf_src.width}")
            print("The script assumes H123 row/col indices match both rasters. Resample/register CF first if they do not match.")

        profile_diag = build_profile_diagnostics(h123, dem_src, cf_src)

        # Filled flags are inherited from the H123 CSVs. This script does not recalculate
        # the filled-crater slope criterion. If any record/profile for a crater has
        # crater_filled_flag or profile_filled_flag, all directions of that crater are skipped.
        crater_filled = {}
        for name, sub in h123.groupby("name", sort=False):
            flags = []
            for key, info in profile_diag.items():
                if key[0] == name:
                    flags.append(bool(info.get("crater_filled_flag_from_csv", False)))
                    flags.append(bool(info.get("profile_filled_flag", False)))
            crater_filled[name] = any(flags)

        records = []
        for _, rec in h123.iterrows():
            pkey = profile_key(rec)
            pinfo = profile_diag.get(pkey, {})
            cflag = bool(crater_filled.get(str(rec["name"]), False))
            records.append(calculate_direction_record(dem_src, cf_src, rec, pinfo, cflag))

        out_df = pd.DataFrame(records)
        out_df = attach_felsic_felsic_profile_thickness(out_df)

        annotated_csv = out_dir / "h123_with_filled_and_basalt_flags.csv"
        thickness_csv = out_dir / "basalt_thickness_direction_records.csv"
        summary_csv = out_dir / "basalt_thickness_crater_profile_summary.csv"
        out_shp = out_dir / "basalt_thickness_points.shp"

        out_df.to_csv(thickness_csv, index=False, encoding="utf-8-sig")

        # Annotated H123-like table, useful for checking which records were excluded.
        flag_cols = [
            "name", "profile_type", "side", "source_step", "reason",
            "crater_filled_flag", "profile_filled_flag", "filled_slope_ratio_le1",
            "profile_basalt_only_unpenetrated", "profile_all_between_basalt",
            "peak_cf", "rim_type_new", "calculation_status", "thickness_mode",
            "h1", "h2", "h2_basalt", "thickness_or_depth", "profile_t_basalt",
            "peak_row", "peak_col", "bottom_row", "bottom_col", "h_basalt_row", "h_basalt_col"
        ]
        for c in flag_cols:
            if c not in out_df.columns:
                out_df[c] = np.nan
        out_df[flag_cols].to_csv(annotated_csv, index=False, encoding="utf-8-sig")

        # Profile-level summary.
        summary_rows = []
        for (name, profile_type), sub in out_df.groupby(["name", "profile_type"], sort=False):
            first = sub.iloc[0]
            summary_rows.append({
                "name": name,
                "profile_type": profile_type,
                "crater_filled_flag": bool(first.get("crater_filled_flag", False)),
                "profile_filled_flag": bool(first.get("profile_filled_flag", False)),
                "filled_slope_ratio_le1": safe_float(first.get("filled_slope_ratio_le1")),
                "profile_basalt_only_unpenetrated": bool(first.get("profile_basalt_only_unpenetrated", False)),
                "left_status": str(sub[sub["side"].eq("left")]["calculation_status"].iloc[0]) if np.any(sub["side"].eq("left")) else "",
                "right_status": str(sub[sub["side"].eq("right")]["calculation_status"].iloc[0]) if np.any(sub["side"].eq("right")) else "",
                "left_mode": str(sub[sub["side"].eq("left")]["thickness_mode"].iloc[0]) if np.any(sub["side"].eq("left")) else "",
                "right_mode": str(sub[sub["side"].eq("right")]["thickness_mode"].iloc[0]) if np.any(sub["side"].eq("right")) else "",
                "profile_t_basalt": safe_float(first.get("profile_t_basalt")),
                "profile_t_basalt_status": str(first.get("profile_t_basalt_status", "")),
            })
        pd.DataFrame(summary_rows).to_csv(summary_csv, index=False, encoding="utf-8-sig")

        write_point_shp(out_df, out_shp, cf_src)

    print(f"Annotated CSV saved: {annotated_csv}")
    print(f"Thickness direction CSV saved: {thickness_csv}")
    print(f"Profile summary CSV saved: {summary_csv}")
    print("Done.")


if __name__ == "__main__":
    main()
